cloud-bulldozer/e2e-benchmarking

workloads/run_perf_test.sh

fix creation of subscription

---

workloads/network-perf/run_hostnetwork_network_test_fromgit.sh

Add hostnetwork network test

---

workloads/Dockerfile
workloads/etcd-perf/Dockerfile
workloads/etcd-perf/run_etcd_tests_fromgit.sh

Move Dockerfile to the etcd-perf directory

Dockerfile for etcd benchmark

---

workloads/etcd-perf/run_etcd_tests_fromgit.sh

Remove latency threshold from etcd test

---

workloads/network-perf/run_multus_network_tests_fromgit.sh
workloads/network-perf/run_pod_network_test_fromgit.sh
workloads/network-perf/run_serviceip_network_test_fromgit.sh

This will give us the ability to run uperf test with 1,2 and 4 client-server pairs from a single script
@jtaleric

add multiple client-server pair test case

---

workloads/network-perf/compare.py

also added a the ability to compare both 'stream' and 'rr' numbers against a reference. @jtaleric

Accept tolerance as an arg

---

workloads/network-perf/compare.py
workloads/network-perf/run_hostnetwork_network_test_fromgit.sh
workloads/network-perf/run_multus_network_tests_fromgit.sh
workloads/network-perf/run_pod_network_test_fromgit.sh
workloads/network-perf/run_serviceip_network_test_fromgit.sh

add metadata_collection as ENV var and increase the timeout

---

workloads/network-perf/run_network_compare.sh

Compare the results of two UPerf UUIDs

Run compare across two UUIDs

---

workloads/etcd-perf/run_etcd_tests_fromgit.sh

Fix unit printing on etcd test

---

workloads/network-perf/run_hostnetwork_network_test_fromgit.sh
workloads/network-perf/run_multus_network_tests_fromgit.sh
workloads/network-perf/run_pod_network_test_fromgit.sh
workloads/network-perf/run_serviceip_network_test_fromgit.sh

Pipeline will report a failure(Azure) much sooner with this commit
@jtaleric 
@chaitanyaenr

adds ability to check if the cluster is up before running the test

---

workloads/network-perf/common.sh
workloads/network-perf/run_hostnetwork_network_test_fromgit.sh
workloads/network-perf/run_multus_network_tests_fromgit.sh
workloads/network-perf/run_pod_network_test_fromgit.sh
workloads/network-perf/run_serviceip_network_test_fromgit.sh

There was a lot of identical code in the network test scripts. This attempts to reuse them by simply adding in the common.sh script first.

Adding common.sh file for simple code reuse

---

workloads/network-perf/common.sh

This fixes https://github.com/cloud-bulldozer/ripsaw/issues/317

Allowing host network in the restricted scc

---

workloads/network-perf/common.sh
workloads/network-perf/smoke_test.sh

helps with testing the changes to the scale-ci-pipeline

add smoke test for uperf workload

---

workloads/network-perf/run_network_compare.sh
workloads/router-perf/run_router_test.sh

compare.yaml files will be created in /network-perf instead of /network-perf/touchstone as we are installing touchstone with pip

fix path for yaml files; add ns arg for query

---

workloads/network-perf/common.sh
workloads/scale-perf/README.md
workloads/scale-perf/common.sh
workloads/scale-perf/requirements.txt
workloads/scale-perf/run_scale_fromgit.sh

Adding scaling to the e2e test scripts

Adding scaling to e2e test scripts

---

workloads/router-perf/run_router_test.sh

the `oc logs -f` command disconnects after a few hours. This commit adds 5 retries 
Avoids https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/ATS-SCALE-CI-HTTP/256/console

add retries to stream logs

---

workloads/network-perf/common.sh

fix - have client-server_pairs be an array instead of a string

---

workloads/etcd-perf/run_etcd_tests_fromgit.sh

Replace BYOWL by fio-distributed and use hostPath to improve etcd IO emulation.

Update etcd workload to use snafu's FIO

---

workloads/upgrade-perf/README.md
workloads/upgrade-perf/common.sh
workloads/upgrade-perf/run_upgrade_fromgit.sh

Add an upgrade test to the e2e scripts. 
Depends-on: https://github.com/cloud-bulldozer/benchmark-wrapper/pull/216
Until ^ is merged it is targeting my repo for testing.

Add upgrade test to e2e

---

workloads/kube-burner/common.sh
workloads/kube-burner/kube-burner-crd.yaml

Ignore errors when a log streaming error happens

Ignore log streaming errors

---

workloads/network-perf/common.sh
workloads/network-perf/ripsaw-uperf-crd.yaml
workloads/network-perf/run_hostnetwork_network_test_fromgit.sh
workloads/network-perf/run_pod_network_test_fromgit.sh
workloads/network-perf/run_serviceip_network_test_fromgit.sh
workloads/run_compare.sh

most of the logic is transferred to common.sh in a modular fashion
A common crd for all three network types
a la https://github.com/cloud-bulldozer/e2e-benchmarking/tree/master/workloads/kube-burner

refactor uperf e2e

---

workloads/kube-burner/common.sh

Replace tput with bash styling

---

workloads/kube-burner/README.md
workloads/kube-burner/common.sh
workloads/kube-burner/env.sh

Add 20 minutes timeout for job and benchmark-operator creation

---

workloads/network-perf/csv_gen.py

avoids https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/RIPSAW-UPERF/293/console
smoke tested https://docs.google.com/spreadsheets/d/1kvPsutyDcW3NSKb7t3iZGA62iFkxbRg7k_ygnVJwwMU/edit#gid=1110227561

replace test_type.keyword with test_type after touchstone refactor

---

workloads/network-perf/csv_gen.py

evaluate each env var individually

fixing an edge case with gsheet env vars

---

workloads/kube-burner/README.md
workloads/kube-burner/env.sh
workloads/kube-burner/kube-burner-crd.yaml
workloads/kube-burner/run_maxnamespaces_test_fromgit.sh
workloads/kube-burner/run_maxservices_test_fromgit.sh

Max-services, max-namespaces & remote configuration

---

workloads/etcd-perf/run_etcd_tests_fromgit.sh
workloads/network-perf/run_multus_network_tests_fromgit.sh
workloads/network-perf/smoke_test.sh
workloads/run_compare.sh
workloads/scale-perf/common.sh
workloads/scale-perf/run_scale_fromgit.sh
workloads/storage-perf/run_storage_tests_fromgit.sh

Updated github links to benchmark-operator from ripsaw 
Fixes #88

updated git urls

---

workloads/network-perf/ripsaw-uperf-crd.yaml

add to this commit https://github.com/cloud-bulldozer/e2e-benchmarking/commit/d33220045b5472b2e144befe93fa7aaf3e35364b

append the benchmark name with num of pairs

---

workloads/network-perf/common.sh
workloads/network-perf/ripsaw-uperf-crd.yaml
workloads/network-perf/run_pod_network_policy_test_fromgit.sh
workloads/network-perf/run_serviceip_network_policy_test_fromgit.sh

Add scripts for networkpolicy testing

---

workloads/kube-burner/README.md
workloads/kube-burner/common.sh
workloads/kube-burner/env.sh
workloads/kube-burner/run_nodedensity-heavy_test_fromgit.sh
workloads/kube-burner/run_nodedensity_test_fromgit.sh

Depends on https://github.com/cloud-bulldozer/benchmark-operator/pull/517

Update kubelet-density to node-density

---

workloads/kube-burner/README.md
workloads/kube-burner/common.sh

The current implementation does not allow to disable ES indexing. Fixing it.

Fix disable ES indexing

---

workloads/kube-burner/common.sh

The conditional was not working well, updating it.

Fix conditional

---

workloads/network-perf/common.sh

Prevent uperf to land in infra,worker labeled nodes

---

workloads/network-perf/common.sh

Uniq topology zones

---

workloads/kube-burner/README.md
workloads/kube-burner/env.sh
workloads/kube-burner/run_poddensity_test_fromgit.sh

Add pod-density workload

---

workloads/router-perf-v2/common.sh

Fix samples expression

---

ci/env.sh
workloads/network-perf/common.sh

CI was broken because of this commit https://github.com/cloud-bulldozer/e2e-benchmarking/commit/bede0b6b0f1a8dceadf85cf0f888b7627d626e8b

Update CI vars to match new naming

---

utils/scale-ci-diagnosis/env.sh
utils/scale-ci-diagnosis/ocp_diagnosis.sh

Updated Scale Ci diagnosis script to accept directory path for snappy.
File directory path is provided is set using SNAPPY_FILE_DIR env variable, which will be used in this script.

Store file in custom directory for snappy in scale_ci_diagnosis script

---

workloads/router-perf-v2/common.sh

Hope it fixes issues like:
```
curl: (52) Empty reply from server
```

Add retry logic to curl

---

workloads/router-perf-v2/csv_gen.py

added 
```
nargs=1,
``` 
to the parser. This will take the tolerance number from cli as a list instead of string
Also, ran black on the code for readability

tolerances as a list instead of a string

---

workloads/kube-burner/README.md
workloads/kube-burner/common.sh
workloads/kube-burner/env.sh

Make use of the env.sh file to set environment variables

Improve variable handling

---

utils/touchstone-compare/run_compare.sh
workloads/network-perf/common.sh
workloads/router-perf-v2/common.sh
workloads/router-perf-v2/ingress-performance.sh

depends on  https://github.com/cloud-bulldozer/benchmark-comparison/pull/41

change benchamrk-comparison invocation

---

utils/touchstone-compare/run_compare.sh

fix touchstone invocation as per new change

---

workloads/router-perf-v2/ingress-performance.sh

https://jenkins.scalelab.redhat.com/job/INGRESS-PERFORMANCE/169/console

fix compare output file name

---

workloads/logging/common.sh
workloads/logging/env.sh
workloads/logging/files/log_generator.yaml
workloads/logging/run_logging_test.sh

Adds support for running logging tests. This works for both Elasticsearch backed and AWS CloudWatch backed configurations.

Add logging test that supports ES and AWS CloudWatch

---

ci/env.sh
ci/run_ci.sh
utils/common.sh
workloads/etcd-perf/run_etcd_tests_fromgit.sh
workloads/kube-burner/common.sh
workloads/logging/deploy_logging_stack.sh
workloads/network-perf/common.sh
workloads/scale-perf/common.sh
workloads/scale-perf/run_scale_fromgit.sh
workloads/storage-perf/run_storage_tests_fromgit.sh

Adding more checks for confirmation of pod creation and running in workload scripts for better error debugging.

Add more checks in the workloads scripts

---

workloads/logging/common.sh

fixes some conditional logic issue present in the logging workload

hotfix logging status check

---

workloads/router-perf-v2/Containerfile

syncing with https://github.com/jmencak/mb/pull/7

add performance improvements options for intel amd arch

---

ci/env.sh
workloads/scale-perf/run_scale_fromgit.sh

- Remove the existing scale pod and benchmark before each run.
- Set the RUN to 2 for scale perf CI.

Fix scale perf

---

workloads/scale-perf/common.sh
workloads/scale-perf/run_scale_fromgit.sh

Fixes issue with the scale benchmark where subsequent runs dont' work. Also setting the RUNS to default to 1

Scale hotfix

---

utils/snappy-move-results/common.sh

help debug errors in scale-ci-diagnosis

---

utils/snappy-move-results/common.sh

airflow run id fix

---

utils/snappy-move-results/common.sh

fixing cluster version format for snappy

---

workloads/prometheus-sizing/metrics.yaml

Metric profiles have now a new structure: cloud-bulldozer/kube-burner#89

Update metric-profile structure

---

utils/scale-ci-diagnosis/ocp_diagnosis.sh

add network trace and logs along with regular must-gather

add network must-gather

---

workloads/kube-burner/common.sh

Correct the git log message

---

ci/env.sh
utils/touchstone-compare/run_compare.sh
workloads/router-perf-v2/common.sh
workloads/router-perf-v2/env.sh
workloads/router-perf-v2/ingress-performance.sh

CI is currently broken, I think we merged https://github.com/cloud-bulldozer/e2e-benchmarking/pull/169 w/o passing any test.

Improve handling of variables used for comparison

---

workloads/router-perf-v2/common.sh

Code update in common.sh to fix shell execution differences

Code tweak to support Shell execution differences

---

ci/env.sh
utils/common.sh
workloads/etcd-perf/run_etcd_tests_fromgit.sh
workloads/kube-burner/common.sh
workloads/kube-burner/env.sh
workloads/kube-burner/kube-burner-crd.yaml
workloads/logging/common.sh
workloads/logging/files/log_generator.yaml
workloads/network-perf/common.sh
workloads/network-perf/ripsaw-uperf-crd.yaml
workloads/network-perf/run_multus_network_tests_fromgit.sh
workloads/network-perf/smoke-crd.yaml
workloads/router-perf-v2/ingress-performance.sh
workloads/scale-perf/common.sh
workloads/scale-perf/run_scale_fromgit.sh
workloads/storage-perf/run_storage_tests_fromgit.sh

Updates e2e scripts to use new ripsaw deploy commands after the operator-sdk upgrade

Update e2e version of benchmark-operator

---

utils/touchstone-compare/run_compare.sh

fix a conditional which lets you compare to a uuid

---

utils/scale-ci-diagnosis/ocp_diagnosis.sh

This fix is needed to handle must-gather run after each task on airflow

fix must-gather file name 

---

utils/scale-ci-diagnosis/ocp_diagnosis.sh

fixes failing must-gather tasks on airflow

set exit 0 for must-gather

---

workloads/kube-burner/env.sh

https://github.com/cloud-bulldozer/kube-burner/releases/tag/v0.13.2

Bump kube-burner to v.13.2

---

workloads/scale-perf/README.md
workloads/scale-perf/common.sh
workloads/scale-perf/default_scale.yaml
workloads/scale-perf/rosa_scale.yaml
workloads/scale-perf/run_scale_fromgit.sh

Add ROSA related vars to create benchmark file with ROSA related parametrs

add ROSA variables to scale script

---

workloads/kube-burner/metrics-profiles/metrics.yml

Some of the new queries were incorrect, fixing them

Fixing some prometheus queries

---

workloads/kube-burner/workloads/cluster-density/cluster-density.yml
workloads/kube-burner/workloads/pod-density-heavy/pod-density-heavy.yml

Fix errata in objectTemplate location

---

utils/compare.sh

https://github.com/cloud-bulldozer/e2e-benchmarking/issues/276

fix tolerancy rules if-else block

---

workloads/kube-burner/metrics-profiles/acs-metrics.yaml

These will be used in ACS airflow runs.

Add ACS specific metrics

---

workloads/kube-burner/common.sh

The current cleanup still left pods in the namespace, so it never would
cleanup properly.

WIP Fixing the cleanup

---

workloads/kube-burner/common.sh

Fix WORKLOAD var initialization in cleanup.

fix cleaup argument initialization

---

utils/common.sh

fixes failing router test on airflow

fix csv_gen function

---

utils/common.sh

fix relative path for google spreadsheet

---

utils/common.sh

Reverts cloud-bulldozer/e2e-benchmarking#280

Revert "fix csv_gen function"

---

ci/env.sh
utils/common.sh
utils/scale-ci-diagnosis/ocp_diagnosis.sh
workloads/README.md
workloads/baseline-performance/README.md
workloads/baseline-performance/common.sh
workloads/etcd-perf/run_etcd_tests_fromgit.sh
workloads/kube-burner/common.sh
workloads/logging/common.sh
workloads/network-perf/common.sh
workloads/prometheus-sizing/common.sh
workloads/router-perf-v2/common.sh
workloads/scale-perf/run_scale_fromgit.sh
workloads/upgrade-perf/common.sh
workloads/upgrade-perf/run_upgrade_fromgit.sh

Allow an openshift login option in e2e instead of only utilizing kubeconfig for authentication.
https://github.com/cloud-bulldozer/e2e-benchmarking/issues/215

Add oc login option for authentication

---

workloads/kube-burner/common.sh

Small fix for executing the force cleanup steps when ns is not already deleted
Fixes #309 Closes #309

fix kube-burner cleanup function

---

workloads/kube-burner/README.md
workloads/kube-burner/env.sh
workloads/kube-burner/workloads/cluster-density/cluster-density.yml
workloads/kube-burner/workloads/max-namespaces/max-namespaces.yml
workloads/kube-burner/workloads/max-services/max-services.yml
workloads/kube-burner/workloads/node-density-heavy/node-density-heavy.yml
workloads/kube-burner/workloads/node-pod-density/node-pod-density.yml
workloads/kube-burner/workloads/pod-density-heavy/pod-density-heavy.yml

Bump kube-burner to v0.15.1 and preload kube-burner images

---

workloads/network-perf/uperf-touchstone.json

Will improve spreadsheet generation.

Add num_pairs bucket and remove max aggregation

---

workloads/kube-burner/common.sh
workloads/kube-burner/metrics-profiles/metrics.yaml
workloads/kube-burner/run_poddensity_test_fromgit.sh

To exclude `container="POD"` OR `container=""`

regex updated for Memory and CPU metrics

---

workloads/kube-burner/metrics-profiles/metrics-aggregated.yaml
workloads/kube-burner/metrics-profiles/metrics.yaml

Skip series with 0 datapoints to index less documents

---

workloads/router-perf-v2/env.sh
workloads/router-perf-v2/http-perf.yml.tmpl
workloads/router-perf-v2/templates/http-scale-client.yml
workloads/router-perf-v2/workload.py

This does a better job detecting the cluster type in router-perf-v2 so it works in all scenarios. The other one was too specific.

Fix cluster type detection being too specific

---

workloads/kube-burner/README.md
workloads/kube-burner/common.sh
workloads/kube-burner/run.sh
workloads/kube-burner/workloads/node-density-cni-networkpolicy/allow-http.yml
workloads/kube-burner/workloads/node-density-cni-networkpolicy/curl-deployment.yml
workloads/kube-burner/workloads/node-density-cni-networkpolicy/deny-all.yml
workloads/kube-burner/workloads/node-density-cni-networkpolicy/node-density-cni-networkpolicy.yml
workloads/kube-burner/workloads/node-density-cni-networkpolicy/webserver-deployment.yml
workloads/kube-burner/workloads/node-density-cni-networkpolicy/webserver-service.yml
workloads/kube-burner/workloads/node-density-cni/curl-deployment.yml
workloads/kube-burner/workloads/node-density-cni/node-density-cni.yml
workloads/kube-burner/workloads/node-density-cni/webserver-deployment.yml
workloads/kube-burner/workloads/node-density-cni/webserver-service.yml

e2e scripts to impleemnt the new kubelet-density workloads in https://github.com/cloud-bulldozer/benchmark-operator/pull/727

Add CNI focussed node-density workloads

---

workloads/kube-burner/workloads/node-density-cni/curl-deployment.yml
workloads/kube-burner/workloads/node-density-cni/webserver-deployment.yml

Add resource requests for CNI workloads

---

workloads/network-perf/run.sh
workloads/router-perf-v2/templates/nginx-pod.yml

- Adding pod `resource` req for router-perf nginx server pods for even pod distribution.
- Overriding `$PAIRS` for hostnet uperf workload.

nginx pod cpu, mem resource requests

---

workloads/router-perf-v2/http-perf.yml.tmpl

Missed in other PR https://github.com/cloud-bulldozer/e2e-benchmarking/pull/360

adjusted qps burst

---

utils/common.sh
workloads/etcd-perf/run_etcd_tests_fromgit.sh
workloads/router-perf-v2/workload.py

Given that we're using a ES with a https endpoint now...

Skip certificate validation

---

workloads/router-perf-v2/common.sh
workloads/router-perf-v2/env.sh
workloads/router-perf-v2/ingress-performance.sh
workloads/router-perf-v2/tuned-profile.yml

- Add new HAProxy image deployment
- Cleanup

Add HAProxy image mod & a few minor fixes for router-perf

---

workloads/kube-burner/workloads/cluster-density/deployment.yml
workloads/kube-burner/workloads/node-density-heavy/app-deployment.yml
workloads/kube-burner/workloads/node-density-heavy/postgres-deployment.yml

Deployment templates are not right, missing `resources` key for cpu mem requests.
`deployment.spec.template.spec.containers.request` >> `deployment.spec.template.spec.containers.resources.request`

update deployment template with requests

---

workloads/kube-burner/README.md
workloads/kube-burner/alerts-profiles/cluster-density-AWS.yml
workloads/kube-burner/alerts-profiles/cluster-density-AlibabaCloud.yml
workloads/kube-burner/alerts-profiles/cluster-density-Azure.yml
workloads/kube-burner/alerts-profiles/cluster-density-BareMetal.yml
workloads/kube-burner/alerts-profiles/cluster-density-GCP.yml
workloads/kube-burner/common.sh
workloads/kube-burner/env.sh
workloads/kube-burner/grafana-agent.yaml

Platform based alerts mechanism.
If PLATFORM_ALERTING is true, the file ${WORKLOAD}-${platform}.yml will be used as alert-profile.
Also some cleanup an general improvements for the scripts.

Platform based alerts

---

utils/scale-ci-diagnosis/ocp_diagnosis.sh

Current tarball includes all the directory structure, namely $OUTPUT_DIR. With this change only the must-gather directory will be included.

Remove directory must-gather prefix

---

workloads/router-perf-v2/mb-touchstone.json

Add latency p95 back to router results comparison

---

workloads/kube-burner/README.md
workloads/kube-burner/env.sh
workloads/router-perf-v2/README.md
workloads/router-perf-v2/env.sh

Bump kube-burner version to v0.16

---

ci/run_ci.sh
utils/benchmark-operator.sh
workloads/api-load/common.sh
workloads/api-load/run.sh
workloads/cyclictest/common.sh
workloads/network-perf/common.sh
workloads/oslat/common.sh
workloads/scale-perf/common.sh
workloads/testpmd/common.sh

Refactored run_workload method as the same code is duplicated in multiple workloads.
Workloads in which code changes are made and their testing logs
network-perf and scale-perf: http://pastebin.test.redhat.com/1057462
api-load: <a href="https://drive.google.com/file/d/1sYxZlLAyCHB8dnJhBrYYdfAyUJ3eceSd/view?usp=sharing"><img src="https://drive.google.com/file/d/1sYxZlLAyCHB8dnJhBrYYdfAyUJ3eceSd/view?usp=sharing" style="width: 500px; max-width: 100%; height: auto" title="API Load published results" /></a>
cyclic-test: <a href="https://drive.google.com/file/d/1p9j8E4UXomyTZi3LRvs3BFZMNmNDFNpv/view?usp=sharing"><img src="https://drive.google.com/file/d/1p9j8E4UXomyTZi3LRvs3BFZMNmNDFNpv/view?usp=sharing" style="width: 500px; max-width: 100%; height: auto" title="code reach-ability screenshot" …

Refactored run_workload method duplicated in the workloads

---

workloads/upgrade-perf/common.sh
workloads/upgrade-perf/rosa_upgrade.sh
workloads/upgrade-perf/run_upgrade_fromgit.sh

Running upgrade_perf against a ROSA cluster will execute specific script

Add ROSA capabilities to upgrade_perf scripts

---

workloads/kube-burner/workloads/max-namespaces/postgres-deployment.yml
workloads/kube-burner/workloads/node-density-heavy/postgres-deployment.yml
workloads/kube-burner/workloads/node-pod-density/node-pod-density.yml
workloads/prometheus-sizing/prometheus-sizing-churning.yml
workloads/prometheus-sizing/prometheus-sizing-static.yml
workloads/router-perf-v2/templates/nginx-deploy.yml

Updating images for workloads to support ARM in addition to x86. Changes for other workloads to follow.

Update workloads with multiarch images for ARM testing support

---

workloads/hyper-scale/README.md
workloads/hyper-scale/common.sh
workloads/hyper-scale/env.sh
workloads/hyper-scale/run.sh

- Hypershift install args
- Hypershift CLI install inputs
- Indexing management cluster stats
- Firewall changes

hypershift e2e script changes

---

workloads/kube-burner/README.md
workloads/kube-burner/common.sh
workloads/kube-burner/run.sh
workloads/kube-burner/workloads/networkpolicy/README.md
workloads/kube-burner/workloads/networkpolicy/case2-networkpolicy.yml
workloads/kube-burner/workloads/networkpolicy/case2.yml
workloads/kube-burner/workloads/networkpolicy/case3-networkpolicy.yml
workloads/kube-burner/workloads/networkpolicy/case3.yml
workloads/kube-burner/workloads/networkpolicy/clusterrole.yml
workloads/kube-burner/workloads/networkpolicy/clusterrolebinding.yml
workloads/kube-burner/workloads/networkpolicy/deny-all.yml
workloads/kube-burner/workloads/networkpolicy/image/Dockerfile
workloads/kube-burner/workloads/networkpolicy/image/init.sh
workloads/kube-burner/workloads/networkpolicy/image/pod-scraper.py
workloads/kube-burner/workloads/networkpolicy/image/requirements.txt
workloads/kube-burner/workloads/networkpolicy/nginx.yml
workloads/kube-burner/workloads/networkpolicy/service.yml

Check out networkpolicy/README below
Cases 1 and 4 are not in this PR's scope
TODO

add networkpolicy wkld

---

workloads/kube-burner/README.md
workloads/kube-burner/common.sh
workloads/kube-burner/run.sh
workloads/kube-burner/workloads/pods-service-route/curl-deployment.yml
workloads/kube-burner/workloads/pods-service-route/pods-service-route.yml
workloads/kube-burner/workloads/pods-service-route/webserver-deployment.yml
workloads/kube-burner/workloads/pods-service-route/webserver-route.yml
workloads/kube-burner/workloads/pods-service-route/webserver-service.yml

This scenario emulates a popular customer usecase.

Add new workload focussed on networking

---

workloads/kube-burner/workloads/networkpolicy/image/pod-scraper.py

dev ES instance doesn't require ssl but prod does

add ssl and timestamp to netpol workload

---

LICENSE

Add License file
Description
This commit proposes an Apache v2 license. Need ack from all current contributors.

add apache v2 license

---

workloads/kube-burner/alerts-profiles/ci.yml
workloads/kube-burner/alerts-profiles/cluster-density-Azure.yml
workloads/kube-burner/alerts-profiles/cluster-density.yml

Fixing typo

---

workloads/hyper-scale/common.sh
workloads/hyper-scale/run.sh

This PR adds the following
* Pre-flight checks
* Clones the hypershift to temp directory
* Clean up kubeadmin configs and other generated files
Signed-off-by: Krishna Harsha Voora <krvoora@redhat.com>

Add pre-flight checks

---

workloads/kube-burner/common.sh
workloads/network-perf/common.sh
workloads/prometheus-sizing/common.sh

- Fixes: https://github.com/cloud-bulldozer/e2e-benchmarking/issues/480

Add duration flag

---

utils/common.sh
workloads/kube-burner/common.sh
workloads/kube-burner/metrics-profiles/hypershift-metrics.yaml

- Fixed metadata collection
- Added mgmt node metrics

updated metrics for hypershift clusters

---

workloads/kube-burner/README.md
workloads/kube-burner/common.sh

For dev purposes it's useful to provide the option of using a kube-burner binary built from source.

Option to build kube-burner from source

---

workloads/hyper-scale/common.sh

This PR aims to stage the required binaries to /tmp
location and not override the system defaults.
Signed-off-by: Krishna Harsha Voora <krvoora@redhat.com>

Stage binaries to temp location

---

utils/touchstone-configs/netobserv_touchstone.json

Doing in conjuncture with https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/283

Added NetObserv touchstone config file

---

workloads/hyper-scale/common.sh

This PR aims at cleaning-up type A record entries first,
and then associated hosted zone(s)
Signed-off-by: Krishna Harsha Voora <krvoora@redhat.com>

Update cleanup() script

---

workloads/kube-burner/env.sh

Need to update the kube-burner verison to include proxy settings for private clusters

Updating kube burner version

---

workloads/kube-burner/common.sh

Updating the path of rendered `metrics.yml` to be dynamic using `KUBE_DIR` env var.

updated path for metric.yaml

---

workloads/kube-burner/common.sh
workloads/kube-burner/env.sh
workloads/kube-burner/metrics-profiles/hypershift-metrics.yaml
workloads/kube-burner/workloads/managed-services/cluster-density.yml

1. kube-burner job pause argument to delay scrapping.
2. Adding IOPS metric for hypershift cluster profile
~~Dependency - https://github.com/cloud-bulldozer/kube-burner/pull/194~~

adding kube-burner job pause var

---

workloads/router-perf-v2/common.sh

fix hypershift condition
One more fix similar to https://github.com/cloud-bulldozer/e2e-benchmarking/pull/503

fix hypershift condition

---

workloads/kube-burner/workloads/max-namespaces/app-deployment.yml
workloads/kube-burner/workloads/max-namespaces/postgres-deployment.yml
workloads/kube-burner/workloads/max-namespaces/postgres-service.yml
workloads/kube-burner/workloads/node-density-cni-networkpolicy/curl-deployment.yml
workloads/kube-burner/workloads/node-density-cni-networkpolicy/webserver-deployment.yml
workloads/kube-burner/workloads/node-density-cni/curl-deployment.yml
workloads/kube-burner/workloads/node-density-cni/webserver-deployment.yml
workloads/kube-burner/workloads/node-density-heavy/app-deployment.yml
workloads/kube-burner/workloads/node-density-heavy/postgres-deployment.yml
workloads/kube-burner/workloads/node-density-heavy/postgres-service.yml
workloads/kube-burner/workloads/pods-service-route/curl-deployment.yml
workloads/kube-burner/workloads/pods-service-route/webserver-deployment.yml

Removes removed portalIP and non-existent spec.triggers

---

workloads/kube-burner/run.sh

pod-density-heavy was pointing to node-density-heavy workload, but is indeed a unique workload.
Also: Since it is a pod density test, I updated the workload to use the PODS_PER_NODE calculation used for the other node-density tests.

Fix pod-density-heavy config file and update to calculate PODS_PER_NODE

---

workloads/kube-burner/workloads/max-namespaces/app-deployment.yml

I forgot to update the perfapp image location in the max-namespaces workload...

Update image location

---

utils/touchstone-configs/netobserv_touchstone.json

Adding totals of resource utilization.

Netobserv touchstone config update

---

workloads/upgrade-perf/rosa_upgrade.sh

Seems like is required in latest versions
```
[2023-01-25, 18:53:11 UTC] {subprocess.py:92} INFO - + rosa upgrade cluster -c perf-411-a212 --version=4.12.0 -y --schedule-date 2023-01-25 --schedule-time 19:00
[2023-01-25, 18:53:12 UTC] {subprocess.py:92} INFO - IAM Roles/Policies upgrade mode:  [Use arrows to move, type to filter, ? for more help]
[2023-01-25, 18:53:12 UTC] {subprocess.py:92} INFO - > auto
[2023-01-25, 18:53:12 UTC] {subprocess.py:92} INFO -   manual
[2023-01-25, 18:53:12 UTC] {subprocess.py:92} INFO - ERR: Expected a valid role upgrade mode: EOF
```
cc: @mohit-sheth @dry923

Add -m flag to ROSA upgrade

---

utils/touchstone-configs/crio.json
utils/touchstone-configs/etcd.json
utils/touchstone-configs/kubelet.json
utils/touchstone-configs/nodeWorkers.json
workloads/kube-burner/metrics-profiles/metrics-ovn.yaml
workloads/kube-burner/metrics-profiles/metrics.yaml

Want to add comparison config files to be used in collecting more data in runs

Compare configs for nodeMemoryUtilization-Masters and etcd, crio, kubelet

---

workloads/kube-burner/README.md
workloads/kube-burner/common.sh
workloads/kube-burner/env.sh
workloads/kube-burner/run.sh

Reverts cloud-bulldozer/e2e-benchmarking#537

Revert "Adding multiple endpoints support for kube-burner workloads"

---

workloads/kube-burner/workloads/managed-services/baseconfig.yml

Updated a base config template for hypershift workload

hypershift: removed deprecated kube-burner config

---

workloads/network-perf-v2/run.sh

Removing time as it was for an experiment.

Remove time

---

workloads/network-perf-v2/env.sh
workloads/network-perf-v2/run.sh

k8s-netperf have now been moved to cloud-bulldozer.

K8s netperf move to cb

---

workloads/kube-burner/workloads/node-density-cni-networkpolicy/node-density-cni-networkpolicy.yml

Template is missing closing `}`
fixes #565

Fix template error

---

workloads/network-perf-v2/env.sh

Update to latest k8s-netperf version

---

workloads/network-perf-v2/env.sh

k8s-netperf bump to 1.9

---

workloads/ingress-perf/.gitignore
workloads/ingress-perf/README.md
workloads/ingress-perf/config/aws-standard.yml
workloads/ingress-perf/run.sh

Some results: https://grafana.rdu2.scalelab.redhat.com:3000/goto/IYxDSH_Vk?orgId=1

Initial implementation of the ingress-perf benchmark

---

workloads/kube-burner-ocp-wrapper/README.md

These links are broken b/c of the versioned docs

Fix broken links

---

workloads/kube-burner-ocp-wrapper/README.md
workloads/kube-burner-ocp-wrapper/run.sh

We should provide the option to completely disable indexing

Disable indexing when ES_SERVER is empty

---

workloads/network-perf-v2/README.md

Adding network-v2 readme.
fixes #580

netv2 readme

---

workloads/network-perf-v2/env.sh

There will eventually be another bump once we change the comparison code.

Bump to k8s-netperf

---

workloads/network-perf-v2/env.sh

Quick fix for an IPSEC issue identified in prow
- Closes #

Quick version bump

---

workloads/kube-burner-ocp-wrapper/run.sh

I think we can move this code to the hypershift() function

Index MC config metadata only when hypershift is detected

---

workloads/kube-burner/workloads/cluster-density/cluster-density.yml
workloads/kube-burner/workloads/concurrent-builds/concurrent-builds.yml
workloads/kube-burner/workloads/managed-services/cluster-density.yml
workloads/kube-burner/workloads/max-namespaces/max-namespaces.yml
workloads/kube-burner/workloads/max-services/max-services.yml
workloads/kube-burner/workloads/networkpolicy/case1.yml
workloads/kube-burner/workloads/networkpolicy/case2.yml
workloads/kube-burner/workloads/networkpolicy/case3.yml
workloads/kube-burner/workloads/node-density-cni-networkpolicy/node-density-cni-networkpolicy.yml
workloads/kube-burner/workloads/node-density-cni/node-density-cni.yml
workloads/kube-burner/workloads/node-density-heavy/node-density-heavy.yml
workloads/kube-burner/workloads/node-pod-density/node-pod-density.yml
workloads/kube-burner/workloads/pod-density-heavy/pod-density-heavy.yml
workloads/kube-burner/workloads/pods-service-route/pods-service-route.yml

pprof collection not getting started because of this typo.

fix typo in pprof collection

---

workloads/ingress-perf/README.md
workloads/ingress-perf/run.sh

This PR updates the README.md
Will allow Mac/Linux users to pull required binary accordingly.
- Closes #

Doc updates

---

workloads/network-perf-v2/env.sh

Bumping version of k8s-netperf
- Closes #

Bump k8s-netperf

---

workloads/ingress-perf/README.md
workloads/ingress-perf/config/standard-classic-rosa.yml
workloads/ingress-perf/run.sh

Classic ROSA already takes care of scheduling the router pods on the infra nodes.
Also bumping ingress-perf version.
- Closes #

Classic ROSA specific configuration

---

workloads/network-perf-v2/README.md
workloads/network-perf-v2/env.sh
workloads/network-perf-v2/run.sh

Use uuidgen to create UUID for k8s-netperf, and export it as a env var. Bump k8s-netperf version
- Closes #

Export UUID / Bump version

---

utils/index.sh
workloads/ingress-perf/run.sh
workloads/kube-burner-ocp-wrapper/run.sh
workloads/kube-burner/run.sh
workloads/network-perf-v2/run.sh

- Closes # https://issues.redhat.com/browse/PERFSCALE-2307
Tested in hacky way with both PROW and AIRFLOW to check if we are getting CI system based metrics.
ES Doc from prow:
```
{
"_index": "perf_scale_ci",
"_type": "_doc",
"_id": "rehearse-41378-periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-gcp-4.13-ocp-qe-perfscale-ci-tests-kube-burner/f9fa4168-1e47-428e-b28c-94c4ad3a16f4/1682062514151493632",
"_version": 1,
"_score": 0,
"_source": {
"ci_system": "PROW",
"uuid": "860fa287-e306-4da9-ba30-b2b106c73784",
"release_stream": "",
"platform": "GCP",
"master_count": 3,
"worker_count": 20,
"infra_count": 3,
"master_type": "e2-standard-4",
"worker_type": "e2-standard-4",
"infra_type": "n1-standard-16",
"total_count": 26,
"cluster_name": "ci-op-1g6yylcx-879ce-g44p9", …
```

Adding common indexer for our CIs

---

workloads/ingress-perf/run.sh
workloads/kube-burner-ocp-wrapper/run.sh
workloads/network-perf-v2/run.sh

Removing the `set- e` before the execution of the benchmark.
- Closes #

Fix up exit codes

---

workloads/kube-burner/common.sh

Hitting error installing kube-burner 
```
08-07 09:28:20.926  tar: /tmp/kube-burner: Cannot open: No such file or directory
08-07 09:28:20.926  tar: Error is not recoverable: exiting now
08-07 09:28:20.926  curl: (23) Failed writing body (2602 != 16375)
08-07 09:28:20.926  [1mMon Aug  7 13:28:20 UTC 2023 Indexing enabled, using metrics from metrics-profiles/metrics.yaml[0m
08-07 09:28:20.926  ~/ws/workspace/multibranch-pipeline_kube-burner/workloads/kube-burner/workloads/node-density-heavy ~/ws/workspace/multibranch-pipeline_kube-burner/workloads/kube-burner
08-07 09:28:20.926  timeout: failed to run command ‘/tmp/kube-burner’: No such file or directory
08-07 09:28:20.926  ~/ws/workspace/multibranch-pipeline_kube-burner/workloads/kube-burner
```
Also the metrics line is duplicated …

Need space to install kube burner tar to folders

---

workloads/network-perf-v2/run.sh

Not capturing the actual time
- Closes #

Fix for jobDuration

---

utils/index.sh

Adding in ci elastic search posts to include runs from jenkins so we will be able to visualize the runs 
- Related Issue # OCPQE-16541
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/kube-burner-ocp/175/console
https://search-ocp-qe-perf-scale-test-elk-hcm7wtsqpxy7xogbu72bor4uve.us-east-1.es.amazonaws.com/_plugin/kibana/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15d,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'5b2a2810-3743-11ee-a6bf-0172abdb9024',key:ciSystem,negate:!f,params:(query:JENKINS),type:phrase),query:(match_phrase:(ciSystem:JENKINS)))),index:'5b2a2810-3743-11ee-a6bf-0172abdb9024',interval:auto,query:(l …

Index jenkins

---

workloads/ingress-perf/config/standard.yml

Increasing requestTimeout has demonstrated to be effective at the time of getting more stable results
- Closes #

Increase requestTimeout

---

workloads/kube-burner-ocp-wrapper/run.sh

Updating kube-burner to the latest version.

Bumping up kube-burner to v1.7.8

---

utils/index.sh

Want to write the data that is written out to elastic search to a file to not need to parse output 
- Closes #
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/kube-burner-ocp/86/console
CC: @nathan-weinberg

write to file

---

workloads/network-perf-v2/env.sh

- Includes fixes to hostNetwork testing
- Includes fixes to empty values
- Closes #

Bumping k8s-netperf version to v0.1.15

---

workloads/kube-burner-ocp-wrapper/metrics-profiles/hosted-cluster-metrics.yml
workloads/kube-burner-ocp-wrapper/metrics-profiles/mc-metrics.yml
workloads/kube-burner-ocp-wrapper/run.sh

Updated hypershift metric profiles to only read serving and non-serving nodes

---

workloads/kube-burner-ocp-wrapper/metrics-profiles/mc-metrics.yml

Updated serving memory utilization query

---

workloads/ingress-perf/run.sh

I removed download_binary by mistake, fixing it

Fix errata

---

utils/index.sh

Changing cluster nodes metadata logic to bring it inline with [go-commons](https://github.com/cloud-bulldozer/go-commons/blob/main/ocp-metadata/ocp-metadata.go#L209-L237).
Related slack thread: https://redhat-internal.slack.com/archives/C05CDC19ZKJ/p1698882978201349
Tested the new logic on my self managed cluster and verified the node counts and types
```
Master Nodes: 3 (Type: m5.4xlarge)
Infra Nodes: 0
Worker Nodes: 3 (Type: m5.4xlarge)
All Nodes: 6
```

Metadata logic change in index.sh script

---

workloads/network-perf-v2/env.sh

- Adds additional error checking
- Closes #

Update k8s-netperf to v0.1.17

---

workloads/kube-burner-ocp-wrapper/run.sh

This PR attempts a retry in case the download is
unsuccessful
This PR attempts a retry in case the download is
unsuccessful
- Related Issue # [PERFSCALE-2577](https://issues.redhat.com/browse/PERFSCALE-2577) 
- Closes # [PERFSCALE-2577](https://issues.redhat.com/browse/PERFSCALE-2577) 

[PERFSCALE-2577] Retry kb download

---

workloads/kube-burner-ocp-wrapper/run.sh

Results from this version are quite aligned with the old ones:
Includes:
- https://github.com/cloud-bulldozer/kube-burner/pull/491
- https://github.com/cloud-bulldozer/kube-burner/pull/497
- https://github.com/cloud-bulldozer/kube-burner/pull/503
- https://github.com/cloud-bulldozer/kube-burner/pull/506
- https://github.com/cloud-bulldozer/kube-burner/pull/508
- Closes #

Kube-burner v1.7.12

---

workloads/network-perf-v2/README.md
workloads/network-perf-v2/env.sh

Movintg to v0.1.19 and increase timeout to match Prow timeout.
- Closes #

Increase k8s-netperf timeout and version

---

workloads/ingress-perf/run.sh

Highlights at https://github.com/cloud-bulldozer/ingress-perf/releases/tag/v0.4.0
- Closes #

Bump ingress-perf

---

utils/index.sh

Adds new fields for metadata
- fips
- ipsec
- encryption
- encryption type
- publish
- Closes #

Adds new fields for metadata

---

utils/index.sh

Fixes typo in calling method `get_ipsec_config`
- Closes #

Fixes typo in calling method

---

utils/index.sh

* Fixes error obtaining FIPS config
* Fixes error on malformed JSON to index
- Closes #

Fixes error obtaining FIPS config

---

workloads/ingress-perf/run.sh
workloads/kube-burner-ocp-wrapper/run.sh
workloads/network-perf-v2/README.md
workloads/network-perf-v2/env.sh

Setting up versioning for all the individual tools so that they can be overridden from PROW.
Subsequent PR: https://github.com/openshift/release/pull/46763 to test once this PR get merged. 
- Related Issue # https://issues.redhat.com/browse/PERFSCALE-2702
Tested these changes in local env by executing those snippets added.

setting up ENVs for overrides

---

workloads/network-perf-v2/README.md
workloads/network-perf-v2/env.sh
workloads/network-perf-v2/run.sh

Needed to add the rest of the vars that are hardcoded/missing but thought it may be handy to have a way to exclude the var from the command.
- Refactor parameter generation
- Add new variables & sort alphabetically
- Remove `arch` command to get system architecture
- Minor checks and style changes
MicroShift 4.14.5
Try to run `run.sh`, changing environment variables optional.

Support local k8s-netperf execution

---

workloads/ingress-perf/config/standard-classic-rosa.yml

We should use the same request timeout in rosa and self-managed clusters
- Closes #

Bump timeout to 10s in rosa tests

---

utils/index.sh

Fixing the encryption query. Tested locally.
- Closes #

Fix encryption query

---

workloads/kube-burner/workloads/networkpolicy/image/pod-scraper.py
workloads/kube-burner/workloads/networkpolicy/image/requirements.txt

Updating pod-scraper code for [network policy workload](https://github.com/cloud-bulldozer/kube-burner/pull/404)

update netpol workload image

---

workloads/router-perf-v2/ingress-performance.sh

With Mr. Sandman deprecated we need the `index_data.json` to be generated for our last round of Perf runs with this workload before we fully move to `ingress-perf`
- Related Issue [NETOBSERV-1330](https://issues.redhat.com/browse/NETOBSERV-1330)
To come

Add data collection to router-perf

---

workloads/kube-burner-ocp-wrapper/README.md
workloads/kube-burner-ocp-wrapper/run.sh

Integrating `kube-burner-ocp` v1.0.0, built using the most recent code.
This "new" binary uses the code from the https://github.com/kube-burner/kube-burner-ocp repository, repository depending on the original `kube-burner` repo.
An ADR doc is pending from my side to be written to track this change. 
- Closes #

kube-burner-ocp integration

---

utils/common.sh

Workaround for https://github.com/burnash/gspread/issues/1385

Pin gspread version to 5.12.4

---

prow/Dockerfile

Adding prow container file to e2e.
- Related Issue # https://issues.redhat.com/browse/PERFSCALE-2731 
These changes can only be verified in PROW: https://github.com/openshift/release/pull/48576

Adding prow containerfile to e2e

---

prow/Dockerfile

Copying source code into PROW dockerfile.
JIRA: https://issues.redhat.com/browse/PERFSCALE-2731
- Related Issue: https://issues.redhat.com/browse/PERFSCALE-2731
The PR needs to be merged to be tested in PROW. But verified its working in local.

Copying source code in PROW dockerfile

---

prow/Dockerfile

Updating source perms in Dockerfile

---

prow/Dockerfile

Updating PROW docker so that it doesn't clone the source code as it of no use.

Updating PROW docker

---

OWNERS

Adding OWNERS file for PR reviews.
Part of this issue: https://issues.redhat.com/browse/PERFSCALE-2571
After merging, can be tested through PR reviews.

Adding ONWERS file for e2e PRs

---

utils/index.sh

Updates IPSEC method for 4.15
This should also avoid the errors that have been appearing in older versions
- Closes #

Updates IPSEC method for 4.15

---

workloads/kube-burner-ocp-wrapper/README.md

Readme update for kube-burner deletion strategy option.
- Closes #

minor update to kb readme

---

workloads/kube-burner-ocp-wrapper/README.md
workloads/kube-burner-ocp-wrapper/egressip.sh
workloads/kube-burner-ocp-wrapper/run.sh

Support egressip scale testing

---

workloads/network-perf-v2/run.sh

Seeing failures due to a change in how we orchestrate the test. See the errors here : https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/network-perf-v2/252/console
- Closes #

Fixing run.sh

---

workloads/kube-burner-ocp-wrapper/run.sh

Create the token inside the script to avoid expiration
- Closes #

Update hypershift on aks to calculate the token

---

workloads/kube-burner-ocp-wrapper/run.sh

Single quotes do not eval the content of the var, fixed with double quotes
- Closes #

Fix quotes on ARO vars

---

workloads/ingress-perf/config/standard-scalelab.yml

I mistakenly configured concurrency 5

Fixing errata in baremetal http2 config

---

workloads/kube-burner-ocp-wrapper/egressip.sh

Delete AWS key if exist and create the new key as we won't be having the pem file for existing key.
Use same name both AWS instance and key.

delete aws key if exist

---

workloads/kube-burner-ocp-wrapper/metrics-profiles/aro/mc-metrics.yml

Include ARO-HCP MC kubelet and containerd metrics
- Closes #

added kubelet and containerd metrics

---

workloads/kube-burner-ocp-wrapper/run.sh

This PR would bypass updating iterations if the WORKLOAD is udn-density-l3-pods
Adds `udn-density-l3-pods` to WORKLOAD Logic
- Closes #

Updates the WORKLOAD condition

---

workloads/kube-burner-ocp-wrapper/run.sh

Adding pprof collection and archive the pprofs
- Closes #

Testing with pprof and archive

---

workloads/kube-burner-ocp-wrapper/run.sh

Bug fix: https://github.com/cloud-bulldozer/e2e-benchmarking/pull/745#issuecomment-2654273530
Needs a run through on one of our CI system

Setting fallback value for ARTIFACT_DIR

---

utils/index.sh

Adds OCP Virtualization metadata

Add CNV metadata

---

workloads/kube-burner-ocp-wrapper/run.sh

Adding full list of trivial kube-burner ocp CI tests.
Related Issue - https://issues.redhat.com/browse/PERFSCALE-3705
Needs this pre-requisite PR: https://github.com/openshift/release/pull/62123 to be merged for testing.

Adding support for trivial CI tests

---

utils/index.sh

Add CNV tuning policy metadata.

[PERFSCALE-3396] CNV tuning policy metadata

---

workloads/kube-burner-ocp-wrapper/egressip.sh

Preparing egress-ip to successfully execute in prow CI.
- Closes # https://issues.redhat.com/browse/PERFSCALE-3705
Verified the functionality in prow CI. Successful run: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/62205/rehearse-62205-pull-ci-cloud-bulldozer-e2e-benchmarking-master-e2e-egressip-single-node/1896708879081803776

Make egress-ip CI ready

---

utils/index.sh

Removing unnecessary timestamps that are not being used anywhere.
Related Issue # https://redhat-internal.slack.com/archives/C05CDC19ZKJ/p1741181721512819
Tested an verified in local. Since its just fields removal, should be fine.

Remove unnecessary timestamp fields

---

workloads/kube-burner-ocp-wrapper/run.sh

Integrating support for rds-core
- Closes # https://issues.redhat.com/browse/PERFSCALE-3705
Tested and verified in prow: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/62177/rehearse-62177-pull-ci-cloud-bulldozer-e2e-benchmarking-master_metal-e2e-rds-core-mno/1902037444618883072

Adding support for rds-core

---

.github/ISSUE_TEMPLATE/bug_report.md
OWNERS

Keeping this aligned with recent contributions and responsibilities.

Update owners and bug assignees

---

workloads/kube-burner-ocp-wrapper/run.sh

Bumping up kube-burner version to v1.6.4
Will verify through PR rehearsals.

Bump up kube-burner version to v1.6.4

---

workloads/kube-burner-ocp-wrapper/metrics-profiles/aro/hosted-cluster-metrics.yml
workloads/kube-burner-ocp-wrapper/metrics-profiles/aro/mc-metrics.yml
workloads/kube-burner-ocp-wrapper/metrics-profiles/rosa/hosted-cluster-metrics.yml

promql changes to capture only worker labelled nodes for HCP
- Closes #

promql changes to capture only worker labelled nodes for HCP

---

workloads/kube-burner-ocp-wrapper/run.sh

Updated curl command to right section
- Closes #

moved curl command to later

---

workloads/kube-burner-ocp-wrapper/run.sh

Add udn-bgp workload

---

workloads/kube-burner/build_helper.sh
workloads/kube-burner/workloads/concurrent-builds/buildconfig_trigger.yml

Make concurrent builds test use the analyze option in the helper script, to only gather the results from Builds that have already ran.
- Related Issue https://github.com/openshift/svt/pull/831

Using analyze option on helper script.
