workloads/run_etcd_tests_fromgit.sh, workloads/run_network_tests.sh, workloads/run_network_tests_fromgit.sh, workloads/run_perf_test.sh, workloads/run_storage_tests_fromgit.sh
k8s nodes was not being captured because nodes were not in the default "view" role. Updated to now create a backpack_role which is the same as "view" with the addition of nodes.
=> Updating backpack view role to include nodes

workloads/network-perf/README.md, workloads/network-perf/compare.py, workloads/network-perf/run_hostnetwork_network_test_fromgit.sh, workloads/network-perf/run_multus_network_tests_fromgit.sh, workloads/network-perf/run_network_compare.sh, workloads/network-perf/run_pod_network_test_fromgit.sh, workloads/network-perf/run_serviceip_network_test_fromgit.sh
@jtaleric @chaitanyaenr
This commit gives us the ability to compare the test_uuid with the baseline_uuid if we set COMPARE=true. Also this commit adds a tuning to specify throughput and latency tolerances individually (default=5). This is because latency can vary a lot depending on the environment (ex. 4.3 perfscale tests). 
The baseline_uuid vars for different tests will be set once they are finalised
=> add the ability to compare 2 uuids from the scripts itself

workloads/network-perf/run_hostnetwork_network_test_fromgit.sh, workloads/network-perf/run_pod_network_test_fromgit.sh, workloads/network-perf/run_serviceip_network_test_fromgit.sh
..also we do not report 8 threads numbers in perfscale reports. The multus script will continue to have  1 and 8 threads as we are currently testing on baremetal-ci
@chaitanyaenr @jtaleric
=> remove 8 threads from the test to reduce CI runtime

workloads/etcd-perf/run_etcd_tests_fromgit.sh, workloads/network-perf/run_hostnetwork_network_test_fromgit.sh, workloads/network-perf/run_multus_network_tests_fromgit.sh, workloads/network-perf/run_pod_network_test_fromgit.sh, workloads/network-perf/run_serviceip_network_test_fromgit.sh, workloads/storage-perf/run_storage_tests_fromgit.sh
Latest change seems that broke openshift upstream CI (https://prow.svc.ci.openshift.org/?job=*etcd-azure-perf-test-daily*) as the kubeconfig file is not in the home directory
By default kubectl and oc clients already look for kube config file at $HOME/.kube/config so it's not required to set it.
=> set KUBECONFIG only when passed as argument

workloads/network-perf/run_hostnetwork_network_test_fromgit.sh, workloads/network-perf/run_multus_network_tests_fromgit.sh, workloads/network-perf/run_pod_network_test_fromgit.sh, workloads/network-perf/run_serviceip_network_test_fromgit.sh
so that it executes in the same shell.
avoids this failure https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/RIPSAW-UPERF/59/console
=> sourcing the common.sh file

workloads/etcd-perf/run_etcd_tests_fromgit.sh, workloads/network-perf/run_hostnetwork_network_test_fromgit.sh, workloads/network-perf/run_multus_network_tests_fromgit.sh, workloads/network-perf/run_pod_network_test_fromgit.sh, workloads/network-perf/run_serviceip_network_test_fromgit.sh, workloads/storage-perf/run_storage_tests_fromgit.sh
This update brings in the metadata definition changes from PR https://github.com/cloud-bulldozer/ripsaw/pull/315 of ripsaw. As such, it needs to be merged after it as well.
Closes #31
=> Updating metadata collection definition PR 315 of ripsaw

workloads/network-perf/run_hostnetwork_network_test_fromgit.sh, workloads/network-perf/run_multus_network_tests_fromgit.sh, workloads/network-perf/run_pod_network_test_fromgit.sh, workloads/network-perf/run_serviceip_network_test_fromgit.sh
The service account variable was changed from sa to serviceaccount. This fixes it here.
=> Fixing metadata variable from sa to serviceaccount

workloads/network-perf/README.md, workloads/network-perf/common.sh, workloads/network-perf/run_hostnetwork_network_test_fromgit.sh, workloads/network-perf/run_multus_network_tests_fromgit.sh, workloads/network-perf/run_pod_network_test_fromgit.sh, workloads/network-perf/run_serviceip_network_test_fromgit.sh
This commit will give us the ability to check the health of the cluster before starting uperf and also while it is running. If the cluster is unhealthy the workload will fail and exit out
Fixes https://github.com/cloud-bulldozer/plow/issues/34
=> Add Cerberus check while running Uperf

workloads/network-perf/README.md, workloads/network-perf/csv_gen.py, workloads/network-perf/run_network_compare.sh
having the keys in central location helps when we are cloning the repo over the existing one ex: scale-ci-pipeline. Also we already have /root/.secrets dir for GCP install and it's service account key. so leveraging that and going forward this location would be good to store creds
rectified edge case
`touchstone_compare ... username:password@$_es:$_es_port     username:password@$_es:$_es_port ... `
instead of 
`touchstone_compare ... username:password@_es:_es_port         _es:_es_port   ... `
which resulted in auth error
=> have the gsheet key in a central location and rectified edge cases

workloads/network-perf/README.md, workloads/router-perf/README.md, workloads/router-perf/csv_gen.py, workloads/router-perf/env.sh, workloads/router-perf/requirements.txt, workloads/router-perf/run_router_compare.sh, workloads/router-perf/run_router_test.sh
similar to uperf we will compare two runs using touchstone https://github.com/cloud-bulldozer/benchmark-comparison/pull/27.
`run_router_test.sh` will be a wrapper which does e2e (initiating, comparing, exporting to gsheet with Pass/Fail) benchmarking.
@jtaleric @chaitanyaenr 
test run https://docs.google.com/spreadsheets/d/1QL77aX2Np-bbz8gLVHJuvng7EYHWK1YGIc2lSWYa-2I/edit#gid=1374708479
=> add router test (mb client) to plow scripts

workloads/etcd-perf/run_etcd_tests_fromgit.sh, workloads/network-perf/common.sh, workloads/router-perf/run_router_test.sh, workloads/scale-perf/common.sh, workloads/storage-perf/run_storage_tests_fromgit.sh
The test could potentially fail if /tmp/ripsaw existed so we'll delete the directory first.
=> Add removal of /tmp/ripsaw before git clone

workloads/network-perf/run_network_compare.sh
A bug that surfaced when the baseline elasticsearch instance and current run's elasticsearch instance are different
=> switch order of uuid

workloads/etcd-perf/run_etcd_tests_fromgit.sh, workloads/storage-perf/run_storage_tests_fromgit.sh
sa was renamed to serviceaccount in the metadata section of the cr.
=> Update for renamed variable

workloads/network-perf/run_serviceip_network_test_fromgit.sh
The ServiceIP test was having issues due to the restricted port range. When metadata collection was done the Elasticsearch ports were not being released so port 20000 was frequently in use and would cause uperf to fail.
=> Setting metadata collection to be done via daemonset for serviceip

workloads/scale-perf/run_scale_fromgit.sh
Adding a status message so we know what the scale is currently at and what is desired.
example output:
```
...
+ echo 'Current worker count: 3'
Current worker count: 3
+ echo 'Desired worker count: 4'
Desired worker count: 4
...
```
=> Add a current/desired worker count status message

workloads/kube-burner/common.sh
When job finishes, the log_streaming loop iterates several times (and therefore printing duplicated logs) before exiting because the benchmark hasn't been marked as Completed|Failed yet. This adds an extra time period to let benchmark-operator update it on time.
=> kube-burner log streaming fix

workloads/network-perf/README.md, workloads/network-perf/common.sh, workloads/network-perf/run_hostnetwork_network_test_fromgit.sh, workloads/network-perf/run_multus_network_tests_fromgit.sh, workloads/network-perf/run_pod_network_test_fromgit.sh, workloads/network-perf/run_serviceip_network_test_fromgit.sh, workloads/network-perf/smoke_test.sh, workloads/router-perf/README.md, workloads/router-perf/run_router_test.sh
With this commit we can use gold-index for comparison. We can also manually add the uuids which will override the gold-index uuids. 
If we want to compare against gold, we need to specify the ocp version to compare against and the sdn type to compare against (defaults to cluster sdn)
Also, we need to specify the elasticsearch server where the gold-index is housed
=> consume gold-index for comparison

workloads/network-perf/run_hostnetwork_network_test_fromgit.sh, workloads/network-perf/run_multus_network_tests_fromgit.sh, workloads/network-perf/run_pod_network_test_fromgit.sh, workloads/network-perf/run_serviceip_network_test_fromgit.sh, workloads/scale-perf/run_scale_fromgit.sh, workloads/storage-perf/run_storage_tests_fromgit.sh
This commit modifies the e2e scripts to avoid deleting the benchmark
at the end of the run to be able to capture the status of the run in
CI. The benchmark is cleaned up before kicking off a new run instead.
=> Avoid deleting the benchmark to track the status in CI

workloads/kube-burner/README.md, workloads/kube-burner/common.sh, workloads/kube-burner/env.sh
The current implementation doesn't verify if a running benchmark is of the kind kube-burner.
=> Fix running kube-burner benchmark

workloads/upgrade-perf/common.sh
The upgrade was not properly passing the ES index/port/server information to snafu. Adding the export in front of the variable definition resolves the issue.
=> Add export to fix indexing issue

workloads/network-perf/common.sh
The backpack_role.yaml was no longer being created after a recent refactoring and would cause a test to fail because it cannot find the backpack-view service account. This adds the apply back in.
=> Apply the backpack_role.yaml

workloads/network-perf/common.sh
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/RIPSAW-UPERF/263/console
avoids 
```
Thu Dec 3 15:09:09 UTC 2020: Current status of the uperf hostnet benchmark with 1 pair/s is Running
Error from server (NotFound): pods "uperf-client-10.0.128.214-885cd499-89l8b" not found
```
=> adding ns to oc command

workloads/network-perf/ripsaw-uperf-crd.yaml, workloads/network-perf/run_multus_network_tests_fromgit.sh, workloads/network-perf/smoke_test.sh
depends on https://github.com/cloud-bulldozer/benchmark-wrapper/pull/229 and https://github.com/cloud-bulldozer/benchmark-operator/pull/469
=> adding run_id to uperf

workloads/network-perf/common.sh, workloads/network-perf/ripsaw-uperf-crd.yaml
there have been clashes for the limited open ports (20000-20011)
this commit enables backpack daemonset mode for serviceip so that we don't see any clashes
=> add metadata.targeted; set it false for serviceip

workloads/kube-burner/common.sh
These nodes sometimes have the worker label, this commit will prevent including them.
=> Update labelSelector to avoid including infra and workload nodes

workloads/kube-burner/README.md, workloads/kube-burner/common.sh, workloads/kube-burner/kube-burner-crd.yaml
We're not counting the kube-burner pod itself when calculating the number of pods to deploy. This is generating issues since this pod can't be scheduled, thus kube-burner times out waiting for it to be ready.
=> Substract kube-burner pod from the node-density pod count

workloads/network-perf/README.md, workloads/network-perf/common.sh
Implement topology anti-affinity logic to place client and server pods. This will help to keep results more stable.
=> Topology anti-affinity

workloads/upgrade-perf/README.md, workloads/upgrade-perf/common.sh, workloads/upgrade-perf/run_upgrade_fromgit.sh
This commit:
- Adds an option to upgrade to the latest version available
in the channel when set.
- Adds support to switch the channel to find the builds for
the upgrade.
=> Add support to upgrade to the latest version

indexing/README.md, indexing/jenkins/README.md, indexing/jenkins/index.sh
This commit adds a script to index jenkins job details including status,
duration, build url, run id etc. into elasticsearch.
=> Add scripts to index jenkins job status

workloads/router-perf-v2/http-perf.yml.tmpl, workloads/router-perf-v2/templates/https-service.yml
Allocate 8443 in passthrough and reencrypt terminations, and 8080 in edge and http terminations.
Prevents running out of ports in large-scale scenarios: 
```
time="2021-03-25 05:08:20" level=error msg="Error creating object: Internal error occurred: failed to allocate a nodePort: range is full"
```
=> Allocate only required ports in services

workloads/kube-burner/README.md, workloads/kube-burner/run_maxnamespaces_test_fromgit.sh, workloads/kube-burner/run_maxservices_test_fromgit.sh
In the Pod Density workload we are using env var named `PODS` here: https://github.com/cloud-bulldozer/e2e-benchmarking/blob/master/workloads/kube-burner/run_poddensity_test_fromgit.sh
For services and namespace workloads we are calling it `JOB_ITERATIONS`. It leads to lack of consistency and potential confusion. 
Variable names for Maximum Namespaces and Services workloads.
Potentially we need a fix in scale-ci jobs where you run these jobs. Please let me know if you'd like me to go there are update it. 
cc: @rsevilla87 @mohit-sheth @chaitanyaenr  @mffiedler
=> Renaming variables in the spirit of consistency

workloads/scale-perf/README.md, workloads/upgrade-perf/README.md
The new way for specifying es user and es password
```
ES_SERVER=https://<user>:<pass>@<es-instance>:<port-no>
```
Confusion over how to pass user:pass
=> deprecate es user and es password vars

workloads/router-perf-v2/common.sh, workloads/router-perf-v2/ingress-performance.sh, workloads/router-perf-v2/workload.py
I have observed a performance degradation that happens during the first iteration of the first test-scenario (also [happens in CI](https://ec2-52-39-240-23.us-west-2.compute.amazonaws.com:8443/job/e2e-benchmarking-ci/61/consoleFull)). I think the reason could be that the static content is not cached by nginx during this first iteration causing it's an extra delay to serve it. This commit adds a new action to the benchmark `test_routes`  to trigger a cURL to all routes before triggering any workload.
We shouldn't observe a big performance degradation of this iteration. (CI can help to verify this)
=> Test routes

workloads/upgrade-perf/README.md, workloads/upgrade-perf/run_upgrade_fromgit.sh
This commit enables to track the upstream channel for nightly OpenShift
builds which are not part of the upgrade path tracked in cincinnati since
it has only the GA builds.
=> Add support to upgrade to OCP nightly builds

workloads/logging/README.md, workloads/logging/deploy_logging_stack.sh, workloads/logging/env.sh, workloads/logging/files/logging-stack_custom_es.yml
Added the ability for a user to pass an external elasticsearch url to use for a custom log forwarder backend.
=> Allow passing a custom elasticsearch backend url to use for log forwarding

workloads/router-perf-v2/README.md, workloads/router-perf-v2/common.sh
Connected to issue #163 
When we run the router perf workload we run it within a pod on OpenShift. Hence instead of trying to sping up another container within there, it seemed as a better option to download kube-burner binary and use it directly. 
I have tested this script locally on my machine as our PSI Jenkins is not available to test. Nonetheless, It should work just fine. 
cc @rsevilla87 @mffiedler @mohit-sheth @chaitanyaenr
=> Adding ability to run kube-burner without the container

workloads/router-perf-v2/README.md, workloads/router-perf-v2/csv_gen.py, workloads/router-perf-v2/requirements.txt
Provide an easy way to install pre-reqs for workload.py and csv_gen.py.
Additionally, update csv_gen.py to not rely on system python3 in case user is running in a virtualenv
Fixes #140 
@rsevilla87 @mohit-sheth PTAL
=> Provide prereqs for Python code for router-perf-v2

workloads/prometheus-sizing/README.md, workloads/prometheus-sizing/common.sh, workloads/prometheus-sizing/env.sh, workloads/prometheus-sizing/metrics.yaml, workloads/prometheus-sizing/prometheus-sizing-churning.sh, workloads/prometheus-sizing/prometheus-sizing-churning.yml, workloads/prometheus-sizing/prometheus-sizing-static.sh, workloads/prometheus-sizing/prometheus-sizing-static.yml, workloads/prometheus-sizing/templates/pod.yml
New prometheus sizing workload. Two variants:
- Static: "Fills" worker nodes with 250 pods and waits 125 minutes before collecting metrics
- Churning: Creates 50 pods per node by default, divided in 8 namespaces by default, and rotates (Deletes that namespace and creates a new one) one these namespace each 15 minutes (by default as well).
=> Prometheus sizing workload

workloads/router-perf-v2/README.md, workloads/router-perf-v2/common.sh
We don't need to manually enter the gold index uuids for comparison. 
We can export 
```
COMPARE_WITH_GOLD=false
LARGE_SCALE_BASELINE_UUID=<uuid>
SMALL_SCALE_BASELINE_UUID=<uuid>
```
to override the gold uuids
=> add ability to compare with gold index

workloads/router-perf-v2/common.sh
During execution of Router ingress perf testing, we found that if we no nodes are labeled as `workload`, we run into failure.
It fixes above issue by selecting one worker node at random and label it as a `workload` node. It is not the ideal solution for all usecases, but in our case all our worker nodes are of same instance type and in that case it would make sense to label any node at random.
cc: @chaitanyaenr @mohit-sheth @mffiedler
=> Add worker node selection for labeling workload nodes

utils/touchstone-compare/run_compare.sh
I saw recently all of my jobs running into error: 
This PR fixes the error by cloning github repo, creating soft-links to config dirs. 
cc @chaitanyaenr @mffiedler @mohit-sheth
=> Fixing run compare.sh to be able to find correct configs

workloads/router-perf-v2/common.sh
Follow up to #171 as that PR added the labels, but too late for the run to succeed. `http-scale-client` deployment waits for the node with correct label and the run fails. 
This PR moves the labeling logic up in the chain so the deployment can succeed.
@mffiedler @mohit-sheth @chaitanyaenr
=> Fix run comapre dot sh

workloads/kube-burner/common.sh
pod_count is not initialized at the beginning, hence there is wrong calculation of already running pods.
=> initialized pod_count

utils/touchstone-compare/run_compare.sh
Removes ERROR lines in the compare.yaml files so that csv_gen.py can parse the yaml file to create a csv
=> remove ERROR lines from touchstone output

workloads/baseline-performance/README.md, workloads/baseline-performance/baseline_perf.sh, workloads/baseline-performance/baseline_perf.yml, workloads/baseline-performance/common.sh, workloads/baseline-performance/metrics.yaml
The baseline performance benchmark is used to measure the performance metrics of the cluster when there are no resources loaded on the cluster. Helps in understanding the baseline performance of the control plane components, nodes, etcd, kubelet etc of Openshift. This way we can identify the bottlenecks in case of regression with respect to minor as well as major releases. The baseline workload will sleep for ${WATCH_TIME} minutes and call kube-burner indexer to collect the metrics without loading the cluster.
https://issues.redhat.com/browse/PERFSCALE-1120
=> Added Baseline Performance Workload

workloads/kube-burner/common.sh, workloads/kube-burner/kube-burner-crd.yaml, workloads/kube-burner/run_clusterdensity_test_fromgit.sh, workloads/kube-burner/run_maxnamespaces_test_fromgit.sh, workloads/kube-burner/run_maxservices_test_fromgit.sh, workloads/kube-burner/run_poddensity_test_fromgit.sh
The JOB_ITERATIONS variable in kube-burner is utilized twice. Once as an input from the user and again in the cr that is applied. This can cause confusion and conflicts when the user sets JOB_ITERATIONS in the env.sh file. This PR changes the variable used within the kube-burner scripts to TEST_JOB_ITERATIONS and applies that in the cr. This avoids reuse of the variable.
=> replace JOB_ITERATIONS with TEST_JOB_ITERATIONS in kube-burner-crd.yaml to avoid conflicts

workloads/logging/common.sh
With the current configuration, the grep do not act over the words on a line, it will be valid when there is at least one pod running, and will include any other status on the count, because wc -w will only count words, not words validated by the grep.
Actual result during the process:
```
$ oc get pod -n my-ripsaw -l job-name=log-generator-f9981cc5 --ignore-not-found -o jsonpath="{.items[*].status.phase}" | grep Running
Pending Pending Pending Running Pending Pending Pending Pending Running Pending Pending Pending Pending Pending Pending Pending Pending Running Pending Pending Pending Running Pending Pending Pending Pending Pending Pending Pending Pending Pending Running Pending Pending Running Pending Pending Pending Pending Pending Pending Pending Pending Pending Pending Pending …
```
=> update conditional to count lines instead of words

workloads/router-perf-v2/common.sh
In router perf test, I got the following error in log.
```
07-09 15:02:22.377  09-07-2021T07:02:20 Generating CSV results
07-09 15:02:22.377  Traceback (most recent call last):
07-09 15:02:22.377    File "./csv_gen.py", line 9, in <module>
07-09 15:02:22.377      from oauth2client.service_account import ServiceAccountCredentials
07-09 15:02:22.377  ModuleNotFoundError: No module named 'oauth2client'
```
Install requirements in common.sh.
=> fix issue of 'oauth2client' not found in csv_gen.py for router-perf-v2

workloads/etcd-perf/run_etcd_tests_fromgit.sh, workloads/kube-burner/env.sh, workloads/logging/common.sh, workloads/network-perf/common.sh, workloads/scale-perf/common.sh, workloads/storage-perf/run_storage_tests_fromgit.sh
This should allow us to merge https://github.com/cloud-bulldozer/benchmark-operator/pull/598 without breaking e2e
=> Pin scripts to pull from v0.1 release of benchmark-operator

workloads/scale-perf/common.sh
hotfixes issue after moving e2e to point to the latest version of benchmark-operator
=> adding backpack role to scale script

workloads/network-perf/common.sh
The README said default should be 10 but script was setting it to 5. 
Fix the defaults to match what README says it should be in https://github.com/cloud-bulldozer/e2e-benchmarking/blob/master/workloads/network-perf/README.md
=> Fix threshold for network latency and throughput tolerance

workloads/network-perf/README.md, workloads/network-perf/common.sh
For providers such as VMware cloud, tests run into an issue due to missing AZs. 
This adds a new variable `NO_AZ` to specify if you are running with the provider with no azs.
cc @mohit-sheth
=> Adding ability to work without zones

workloads/network-perf/common.sh
Zones search is failing on rosa clusters because nodes are labeled on a different way:
$ oc get nodes
NAME                                         STATUS   ROLES          AGE   VERSION
ip-10-0-133-190.us-west-2.compute.internal   Ready    worker         75m   v1.21.1+9807387
ip-10-0-135-251.us-west-2.compute.internal   Ready    infra,worker   51m   v1.21.1+9807387
ip-10-0-141-182.us-west-2.compute.internal   Ready    master         82m   v1.21.1+9807387
ip-10-0-164-185.us-west-2.compute.internal   Ready    worker         73m   v1.21.1+9807387
ip-10-0-166-165.us-west-2.compute.internal   Ready    infra,worker   51m   v1.21.1+9807387
ip-10-0-170-115.us-west-2.compute.internal   Ready    master         82m   v1.21.1+9807387
ip-10-0-194-87.us-west-2.compute.internal    Ready    infra,worker …
=> add infra!= to zones selector as rosa infra nodes as labeled as infra,worker

utils/touchstone-compare/run_compare.sh, workloads/network-perf/README.md, workloads/network-perf/common.sh
fixes benchmark comparison in uperf 
adds new function get_gold_ocp_version to automatically get the cluster version to compare with existing ocp version
Fixes failing airflow uperf runs
=> Fix benchmark comparison in uperf tests

workloads/kube-burner/env.sh, workloads/kube-burner/workloads/cluster-density/cluster-density.yml, workloads/kube-burner/workloads/cluster-density/templates/configmap.yml, workloads/kube-burner/workloads/cluster-density/templates/deployment.yml, workloads/kube-burner/workloads/cluster-density/templates/secret.yml
Configmap and secret data must be strings, double quoting it to prevent issues like the following:
```
oc create -f - << EOF
apiVersion: v1
kind: ConfigMap
metadata:
name: foo
data:
key1: 4
EOF
Error from server (BadRequest): error when creating "STDIN": ConfigMap in version "v1" cannot be handled as a ConfigMap: v1.ConfigMap.ObjectMeta: v1.ObjectMeta.TypeMeta: Kind: Data: ReadString: expects " or n, but found 4, error found in #10 byte of ...|:{"key1":4},"kind":"|..., bigger context ...|{"apiVersion":"v1","data":{"key1":4},"kind":"ConfigMap","metadata":{"name":"temaller"|...
``` 
Where double quoted works like a charm
```
$ oc create -f - << EOF
apiVersion: v1                                    
kind: ConfigMap …
```
=> Fix cluster-density variables

workloads/router-perf-v2/common.sh
In single node deployments we need to scale the number of ingress controllers to zero before setting liveness probe due to the anti-affinity rules of this deployment  and the deployment rollout policy (maxUnavailable is 50%)
- Fixes #220
=> Scale ingress controller down to 0 before setting liveness probe

workloads/kube-burner/run_maxnamespaces_test_fromgit.sh, workloads/kube-burner/run_maxservices_test_fromgit.sh
This PR closes #235, where job iterations for the maxservices and maxnamespaces kube-burner
workloads were being set to 0.
Closes #235
=> Fix in maxnamespaces and maxservices kube-burner workloads

workloads/router-perf-v2/README.md, workloads/router-perf-v2/env.sh
The COMPARE env variable was being used in utils/touchstone_compare/run_compare.sh but was not in the router env.sh or README. If this is not set and the user wants to compare data without the GOLD UUID no comparison is produced.
=> Adding missing env variable to env.sh and README

utils/snappy-move-results/common.sh
snappy part in uperf scripts are failing on airflow, due to error in grep/pipe
disabling -o pipefail should solve this issue by not terminating immediately and return 0 
This error does not occur when a uperf script runs individually, but is seen on airflow dags when run after the control plane tests , 
only the infra lines fail
infra=`oc get nodes -l node-role.kubernetes.io/infra | grep -v NAME -m 1 | awk '{print $1}'`
INFRA_NODE_TYPE=`oc describe node $infra | grep "node.kubernetes.io/instance-type" | grep -oE "[^=]+$"`
possible theories are grep takes too long to find or multiple pipes cause a timeout.
=> fix snappy error due to grep/pipe 

workloads/scale-perf/README.md, workloads/scale-perf/run_scale_fromgit.sh
We're creating a new benchmark with the same uuid just after deleting the previous one, benchmark-operator goes crazy and marks the new one as completed w/o doing nothing.
=> Sleep 10s before next run

workloads/kube-burner/metrics-profiles/metrics-aggregated.yml, workloads/kube-burner/metrics-profiles/metrics.yml
Add per node role memory/cpu metrics, also adding failed pod metrics to ease debugging.
Remove buffers + cached memory (usually useless)
=> CPU and memory by node role plus failed pods breakdown

indexing/jenkins/index.sh, workloads/baseline-performance/common.sh, workloads/kube-burner/common.sh, workloads/network-perf/env.sh, workloads/network-perf/ripsaw-uperf-crd.yaml, workloads/prometheus-sizing/common.sh, workloads/router-perf-v2/env.sh
Ensures e2e checks for the UUID env var before generating a random uuid. If that environment variable exists, it'll use that instead.
=> making e2e scripts use manual uuid if given

workloads/kube-burner/common.sh
Airflow overwrites METRICS_PROFILE and since https://github.com/cloud-bulldozer/e2e-benchmarking/pull/257 those files are in the metrics-profiles directory. This PR should fix these airflow workloads
=> Fix metrics-profile location

workloads/network-perf/env.sh, workloads/network-perf/run_hostnetwork_network_test_fromgit.sh, workloads/network-perf/run_pod_network_policy_test_fromgit.sh, workloads/network-perf/run_pod_network_test_fromgit.sh, workloads/network-perf/run_serviceip_network_policy_test_fromgit.sh, workloads/network-perf/run_serviceip_network_test_fromgit.sh, workloads/network-perf/smoke_test.sh
Uperf run from e2e requires 3 uuids (hn, p2p, p2s). When we set a uuid at a global level all the three test get the same uuid and it is impossible for benchmark-comparison to differentiate between them, for now at least. This commit should initialize different uuids for the 3 tests.
=> have UUID as local variable for networking tests

workloads/router-perf-v2/common.sh
Router test is failing on Airflow executions for ROSA because of this function:
```
[2021-11-16, 16:53:41 CET] {subprocess.py:89} INFO - /home/airflow/workspace/e2e-benchmarking/workloads/router-perf-v2
[2021-11-16, 16:53:41 CET] {subprocess.py:89} INFO - [1mTue Nov 16 15:53:41 UTC 2021 Testing all routes before triggering the workload[0m
[2021-11-16, 16:59:08 CET] {subprocess.py:89} INFO - curl: (92) HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)
```
Route checked is: https://http-perf-reencrypt-1-http-scale-reencrypt.apps.airflow-49-e51a.dny1.s1.devshift.org//1024.html
The double slash is making curl fails:
```
$ curl -k https://http-perf-reencrypt-1-http-scale-reencrypt.apps.airflow-49-e51a.dny1.s1.devshift.org//1024.html
curl: (92) HTTP/2 stream 0 was not closed …
```
=> Remove extra / which is causing errors on reencrypt route tests

workloads/router-perf-v2/env.sh
The way NUM_NODES is calculated currently doesn't account for clusters that tag workload and infra nodes as worker nodes as well. This would result in a miscalculation of workers.
Fix NUM_NODES calculation to account for managed services
=> Adjust NUM_NODES command in router test to account for managed services

utils/common.sh, utils/compare.sh
error: `[2021-11-29, 20:38:02 UTC] {subprocess.py:89} INFO - ../../utils/compare.sh: line 14: deactivate: command not found`. 
This error occurs since we're trying to deactivate venv when it's already been deactivated. This happens because we're creating a virtualenv inside an already existing venv and when we try to deactivate the inner venv, both venv's get deactivated. The second venv is created in generate google spreadsheet function. 
first venv: https://github.com/cloud-bulldozer/e2e-benchmarking/blob/dc5b31b5119605579ccbd1c6eaf6bf4a2f81dc2c/utils/compare.sh#L8 
second venv: https://github.com/cloud-bulldozer/e2e-benchmarking/blob/dc5b31b5119605579ccbd1c6eaf6bf4a2f81dc2c/utils/common.sh#L78 
So a solution is to ignore the first venv's deactivate command if deactivate from the google …
=> fix venv deactivate conflict

workloads/network-perf/run.sh
Current Uperf Scripts for pod and service network tests actually run three separate runs per script invocation (different number of pairs). In Airflow we assume 1 benchmark per task, so we want to run those three in separate tasks. 
This script `run.sh` will just run any generic uperf workload, and take in the necessary params to configure it. We can use this in our Airflow benchmark configs to split out the runs into separate tasks.
=> Uperf single run

workloads/kube-burner/README.md, workloads/kube-burner/env.sh
Interim solution as we should try to replace the hard coded version with a `stable` tag.
- `kube-burner` bug fixes around Elasticsearch (https://github.com/cloud-bulldozer/kube-burner/releases/tag/v0.14.3)
=> Bump default KUBE_BURNER_IMAGE for kube-burner workload

workloads/scale-perf/run_scale_fromgit.sh
https://github.com/cloud-bulldozer/e2e-benchmarking/issues/79
=> print scale up/down timings on stdout

workloads/kube-burner/metrics-profiles/acs-metrics.yaml
These metrics take too long to index (>32mins) and this causes tasks to fail. This PR disables them until they can be usefully aggregated.
=> ACS: Disable metrics that take too long to index

workloads/kube-burner/common.sh, workloads/kube-burner/workloads/cluster-density/cluster-density.yml, workloads/kube-burner/workloads/max-namespaces/max-namespaces.yml, workloads/kube-burner/workloads/max-services/max-services.yml, workloads/kube-burner/workloads/node-density-heavy/node-density-heavy.yml, workloads/kube-burner/workloads/node-pod-density/node-pod-density.yml, workloads/kube-burner/workloads/pod-density-heavy/pod-density-heavy.yml
Remove workload name prefix from namespace expression
So that:
```
time="2022-01-18 11:36:00" level=error msg="Unexpected error creating
namespace
cluster-density-8d06dda5-ae61-4a-cluster-density-1k-20220118-206:
Namespace
\"cluster-density-8d06dda5-ae61-4a-cluster-density-1k-20220118-206\" is
invalid: [metadata.name: Invalid value:
\"cluster-density-8d06dda5-ae61-4a-cluster-density-1k-20220118-206\":
must be no more than 63 characters, metadata.labels: Invalid value:
\"cluster-density-8d06dda5-ae61-4a-cluster-density-1k-20220118-206\":
must be no more than 63 characters]"```
does not happen anymore.
=> Remove workload name prefix from namespace expression

workloads/router-perf-v2/workload.py
In some cases, elastic fails to index the data, throws an error, and fails the workload, which can be resolved on retry.
Added retries to index function to avoid flakiness.
More details on Issue - https://github.com/cloud-bulldozer/e2e-benchmarking/issues/269
closes #269 fixes #269
=> add retries to elastic indexing function for router-perf

ci/run_ci.sh
CI fails when we update any dependency library version in ripsaw because of the existing old installed ripsaw in the CI node.
Adding clean steps before running any ci test to make sure that we do not have any temp ripsaw files from previous runs.
=> clear temp/ripsaw directory before running ci tests

utils/compare.sh
In our test jenkins machines we have both python and python3 installed on our systems. Using python [here](https://github.com/cloud-bulldozer/e2e-benchmarking/blob/528eed64f791ae9856cde8bee082bcd998905c36/utils/compare.sh#L8) results in an error like the below. Are we able to add in python3 specifically here, so that we are able to properly create a python3 virtualenv? Thanks
01-10 15:23:41.990  Mon Jan 10 07:23:41 UTC 2022 Installing touchstone
01-10 15:23:41.990  /usr/bin/python: No module named venv
=> Adding python3 specific version to touchstone installation

workloads/network-perf/README.md, workloads/network-perf/env.sh, workloads/network-perf/ripsaw-uperf-crd.yaml
In bare metal environments the oscillation between test runs is less significant compared with shared cloud ones.
Exposing the number of samples as an option will allow to run faster tests in bare metal scenarios.
=> Expose the number of samples as an option for network workloads

workloads/kube-burner/env.sh
Includes fix for:
```
time="2022-02-22 10:45:41" level=error msg="Unexpected error creating namespace kube-burner: admission webhook \"namespace-validation.managed.openshift.io\" denied the request: Prevented from accessing Red Hat managed namespaces. Customer workloads should be placed in customer namespaces, and should not match an entry in this list of regular expressions: [^kube.* ^default$ ^redhat.* ^acm$ ^addon-dba-operator$ ^codeready-workspaces-operator$ ^codeready-workspaces-operator-qe$ ^openshift-logging$ ^openshift-storage$ ^prow$ ^redhat-addon-operator$ ^redhat-gpu-operator$ ^redhat-kas-fleetshard-operator$ ^redhat-kas-fleetshard-operator-qe$ ^redhat-managed-kafka-operator$ ^redhat-managed-kafka-operator-qe$ ^redhat-ocm-addon-test-operator$ ^redhat-ods-operator$ …
```
=> Bump kube-burner v0.15.2

workloads/network-perf/common.sh
The Job to create server/client use the benchmark-operator scc
that has priveleged access. Moreover this command fails on Managed
Services clusters since you cannot change an existing SCC there.
=> Modifying the default restricted SCC is not required

workloads/kube-burner/metrics-profiles/metrics-aggregated.yaml, workloads/kube-burner/metrics-profiles/metrics.yaml
Get rid of metrics not useful (or too granular) for release reporting (we should use Dittybopper or Thanos for cluster debugging and long term storage of this kind of metrics) , hence reducing the number of indexed documents. and add some of the upstream SLI metrics (https://github.com/kubernetes/community/blob/master/sig-scalability/slos/slos.md#steady-state-slisslos) such as:
- Pod Ready latency
- Network programming latency
- ReadOnly API requests
- Mutating API requests
- Etcd Fsync latency (This is a OpenShift SLI)
Dashboard refactor is also ready: http://grafana.apps.observability.perfscale.devcluster.openshift.com/d/n8_lX3-nk/kube-burner-report-v2?orgId=1&from=1644849374037&to=1644856446517&var-Datasource=Observability%20-%20ripsaw-kube-burner&var-sdn=openshift-sdn&var-job=cluster-d …
=> Kube burner metrics refactor

workloads/network-perf/README.md, workloads/network-perf/run.sh
Host Network tests were originally executed with only 1 pair to prevent uperf server port collision.
Fixes: https://github.com/cloud-bulldozer/e2e-benchmarking/issues/328
=> Run hostNetwork with only 1 pair

utils/benchmark-operator.sh
We're currently blind when a benchmark fails. This change should shed some light to the error detail.
=> Print pod info on error

workloads/kube-burner/README.md, workloads/kube-burner/run.sh
Per https://github.com/cloud-bulldozer/airflow-kubernetes/pull/145 we are aligning to 245 for our node density tests by default.
=> Align default pods per node to new standard of 245

workloads/kube-burner/workloads/node-density-heavy/app-deployment.yml, workloads/kube-burner/workloads/node-density-heavy/postgres-deployment.yml, workloads/kube-burner/workloads/node-pod-density/pod.yml
Setting a minimal pod resources in pods helps the scheduler algorithm to evenly spread the pods across worker nodes. Thanks to this change I've managed to get really good pod latency numbers in OVNKubernetes based clusters.
=> Set pod resources in node-density workloads

utils/benchmark-operator.sh
We shouldn't directly exit 1 on benchmark error. return 1 instead will let the parent script perform the benchmark cleanup before exiting.
=> Don't exit 1 on benchmark error

workloads/kube-burner/metrics-profiles/metrics.yaml
This helps us quickly check if the scheduler did a fair job.
Updated kube-burner dashboard to add a panel related to this.
=> Add metric for pod distribution by node

workloads/kube-burner/metrics-profiles/metrics-aggregated.yaml, workloads/kube-burner/metrics-profiles/metrics.yaml
From my experiments, this metric is similar to the kubeproxy_network_programming_duration_seconds_bucket exposed in kube-proxy (OpenShiftSDN)
ref: https://github.com/ovn-org/ovn-kubernetes/blob/master/go-controller/pkg/metrics/master.go#L130-L136
cc: @dry923 @smalleni @mohit-sheth
=> Add ovnkube_master_sync_service_latency_seconds_bucket metric

utils/common.sh
Including the workload name as metadata field will be useful to perform comparisons. The value of this field, namely WORKLOAD, is already set by the different benchmarks of this repo.
=> Include workload field as metadata

workloads/kube-burner/README.md, workloads/kube-burner/build_helper.sh, workloads/kube-burner/builds/cakephp.sh, workloads/kube-burner/builds/django.sh, workloads/kube-burner/builds/eap.sh, workloads/kube-burner/builds/nodejs.sh, workloads/kube-burner/builds/rails.sh, workloads/kube-burner/common.sh, workloads/kube-burner/env.sh, workloads/kube-burner/run.sh, workloads/kube-burner/workloads/concurrent-builds/buildconfig_trigger.yml, workloads/kube-burner/workloads/concurrent-builds/concurrent-builds.yml, workloads/kube-burner/workloads/concurrent-builds/configmap.yml, workloads/kube-burner/workloads/concurrent-builds/imagestream.yml
This (with addition of benchmark-operator [PR](https://github.com/cloud-bulldozer/benchmark-operator/pull/566)) will add and run the concurrent builds test case 
This is a little different from some of the other scripts in kube-burner because of the need to start **x** number of builds concurrently and get the build and push times. 
Benchmark-operator creates the builds that we can then use to create/start new builds concurrently to get the data for. The benchmark operator makes 1 more namespace then set in the build array to make sure that we can run enough concurrent builds as specified in the build array parameter. 
The results will be outputted into a file named "conc_builds_results.out" and printed out at the end of the run
=> Adding concurrent builds test for benchmark operator

workloads/kube-burner/README.md, workloads/kube-burner/common.sh, workloads/kube-burner/env.sh
Moar vars, in large-scale tests, deleting the created resources can take a while. We should be able to configure this timeout
=> Add CLEANUP_TIMEOUT variable

workloads/kube-burner/run.sh
The string comparison of the type of workload was not working properly. All workloads were getting into the if statement and causing a bunch of problems with running workloads multiple times 
All workloads that aren't concurrent builds to run once and properly
=> Incorrect string comparison for workload type of run

workloads/network-perf/README.md, workloads/network-perf/env.sh
Targeted metadata collection may run into issues with ports in use and fail. Setting this to targeted: false by default.
=> Set targeted to false for metadata collection by default

utils/common.sh, workloads/router-perf-v2/env.sh, workloads/router-perf-v2/http-perf.yml.tmpl, workloads/router-perf-v2/templates/http-scale-client.yml, workloads/router-perf-v2/workload.py
ROSA was failing to be detected as platform, as it is not always the first tag on [utils/common.sh](https://github.com/cloud-bulldozer/e2e-benchmarking/blob/master/utils/common.sh#L128), for example:
```
"platformStatus": {
"aws": {
"region": "us-west-2",
"resourceTags": [
{
"key": "red-hat-managed",
"value": "true"
},
{
"key": "red-hat-clustertype",
"value": "rosa"
}
]
},
"type": "AWS"
}
}
}
```
Current return: true, instead of rosa
Also moving ROSA installation to PLATFORMs instead of CLUSTERTYPE to allow comparing common installations to managed services ones.
Example executing ingress-performance and uploaded to perf-results-elastic.apps.observability.perfscale.devcluster.openshift.com:80
Workload finished, results:
{
"termination": "http",
"test_type": "http",
"uuid": …
=> Modify how ROSA is detected as platform and move from cloud_type to platform

utils/benchmark-operator.sh, workloads/kube-burner/build_helper.sh, workloads/kube-burner/run.sh, workloads/logging/run_logging_test.sh, workloads/network-perf/run.sh, workloads/scale-perf/run_scale_fromgit.sh
Moving remove_cli to after gen metadata so the python virtualenv is still avaiable with pyyaml package. 
Also adding if statement if project_name does not exist in the build helper (was seeing the error under fixes)
https://github.com/cloud-bulldozer/e2e-benchmarking/issues/371
```
04-07 11:40:36.224  No resources found in --no-headers namespace.
04-07 11:40:36.224  build_helper.sh: line 10: ${#project_name}-1: substring expression < 0
```
=> Moving remove cli till after gen metadata and only if failure

workloads/kube-burner/workloads/max-namespaces/postgres-deployment.yml, workloads/kube-burner/workloads/node-density-heavy/postgres-deployment.yml
We should use the unauthenticated repository to prevent auth issues
=> Use unauthenticated repository for postgres image

workloads/router-perf-v2/README.md
Add `HAPROXY_IMAGE` to README.md
Missing docs for router workload
=> Add missing HAPROXY_IMAGE to README

workloads/router-perf-v2/env.sh
This helps differentiate results in the case where
we do multiple runs of the router test from the same directory.
=> Append UUID to result csv

workloads/router-perf-v2/README.md, workloads/router-perf-v2/env.sh, workloads/router-perf-v2/http-perf.yml.tmpl
Also shifting to local engine by default (It's the fastest one and does not depends on podman anymore), and updating to a recent kube-burner version which includes the new template functions introduced at https://github.com/cloud-bulldozer/kube-burner/pull/135
- Fixes: https://github.com/cloud-bulldozer/e2e-benchmarking/issues/362
=> Template out infrastructure to match with TERMINATIONS

workloads/router-perf-v2/README.md, workloads/router-perf-v2/common.sh, workloads/router-perf-v2/env.sh, workloads/router-perf-v2/ingress-performance.sh
Adds the ability to customize the ingress-operator image and adds additional verification and logging for the router image customization.
I would have to do more difficult workarounds for customizing the ingress-operator image. This makes it easier.
=> HAProxy: Add ability to customize the ingress-operator image

utils/common.sh
When no resourceTags are defined, jq cannot iterate over null. Adding a try will create an empty result.
PLATFORM will be the result of the query to the resourceTags if result is not empty
=> Fix clustertype detection on AWS clusters

workloads/kube-burner/workloads/node-density-cni-networkpolicy/curl-deployment.yml, workloads/kube-burner/workloads/node-density-cni/curl-deployment.yml
Does the same for node-density-cni-networkpolicy to improve granularity
of Pod Startup latency.
=> Reduce timeoutSeconds for startupProbe in node-density-cni

workloads/router-perf-v2/common.sh, workloads/router-perf-v2/ingress-performance.sh
Re-scheduling the monitoring stack to worker nodes before the benchmark starts will prevent the benchmark to be affected by prometheus noise (compaction, scraping, etc) and will help us to obtain more deterministic results.
The below graphs show an snippet of the system prometheus system activity during a benchmark
Where the highest CPU spikes happen during the database compaction: ~19:00 and 21:00
There's also a almost constant network I/O activity caused by metric scraping.
Another interesting fact is that we deploy 3 infrastructure nodes and there's only 2 prometheus replicas, so in some tests it's possible to have an ingress-controller in a node w/o any prometheus replica, that means that the test scenario can be different between …
=> Re-schedule monitoring-stack to worker nodes

workloads/kube-burner/run.sh
Want to only fully clean up benchmark-operator namespace and benchmarks when CLEANUP_WHEN_FINISH is set to true, otherwise want to just deactivate/remove the cli 
Note that in previous PR I had added the cleanup of benchmark operator in multiple places, but it looks like the CLEANUP_WHEN_FINISH variable is only for kube-burner workload so only editing this workload
https://github.com/cloud-bulldozer/e2e-benchmarking/pull/372/files
=> Removing benchmark operator only when cleanup when finish is true

workloads/network-perf/uperf-tolerancy-rules.yaml, workloads/network-perf/uperf-touchstone-smoke.json, workloads/network-perf/uperf-touchstone.json, workloads/router-perf-v2/README.md, workloads/router-perf-v2/env.sh, workloads/router-perf-v2/mb-tolerancy-rules.yaml, workloads/router-perf-v2/mb-touchstone.json
With this change, touchstone will report error when there's more than 33% of failures on a comparison block, that is to say,  in the following comparison:
```
+-------------+--------+----------------------+-----------+---------------------+--------+-----------+------------+------------+
|  test_type  | routes | conn_per_targetroute | keepalive |       metric        | result | deviation |    4.9     | 4.11  |
+-------------+--------+----------------------+-----------+---------------------+--------+-----------+------------+------------+
| passthrough |  500   |          1           |     0     | avg(latency_95pctl) |  Pass  |  -2.55%   |   5571.5   |   5429.5   |
| passthrough |  500   |          1           |     1     | avg(latency_95pctl) …
```
=> Max touchstone failures

workloads/network-perf/run.sh
No idea what was the purpose of this variable, but it's useless now.
=> Remobe BASELINE_POD_UUID

utils/common.sh
For some reason we were collecting the cluster_name and no indexing it.
=> Index cluster name

workloads/kube-burner/env.sh
If se set a default value, the METRICS_PROFILE variable is not overriden in the workload, because of the expression `METRICS_PROFILE=${METRICS_PROFILE:-metrics-profiles/metrics-aggregated.yaml}`
The metrics-aggregated profile is not being set in cluster-density tests
=> Remove default value for METRICS_PROFILE

workloads/kube-burner/README.md, workloads/kube-burner/env.sh, workloads/router-perf-v2/README.md, workloads/router-perf-v2/env.sh
Bumping kube-burner version. Changelog: https://github.com/cloud-bulldozer/kube-burner/releases/tag/v0.15.5
cc: @qiliRedHat
=> Bump kube-burner version

workloads/api-load/README.md, workloads/api-load/api-load-crd.yaml, workloads/api-load/common.sh
Currently we are overriding AWS_ACCESS_KEY_ID and
AWS_SECRET_ACCESS_KEY with OsdCcsAdmin user's keys.
Newly created OsdCcsAdmin user's aws token is needed for only
ocm-api-load tool.
So instead of overriding existing aws keys, we can create
OsdCcsAdmin user keys with different variable names.
=> fix aws keys

workloads/kube-burner/common.sh
As of k8s 1.24 the command oc sa get-token is not valid anymore:
```
[root@ip-172-31-32-243 ~]# oc sa get-token -n openshift-monitoring prometheus-k8s 
Command "get-token" is deprecated, and will be removed in the future version. Use oc create token instead.
error: could not find a service account token for service account "prometheus-k8s"
```
Fixing it and adding backwards compatibility.
=> Fix prometheus token expression for k8s 1.24

workloads/kube-burner/common.sh
This export is actually not necessary in this fuction as it's overriding the configured NODE_SELECTOR by node-density=enabled
=> Remove export NODE_SELECTOR

utils/benchmark-operator.sh, workloads/cyclictest/common.sh, workloads/etcd-perf/run_etcd_tests_fromgit.sh, workloads/kube-burner/common.sh, workloads/logging/common.sh, workloads/network-perf/common.sh, workloads/network-perf/ripsaw-uperf-crd.yaml, workloads/network-perf/smoke-crd.yaml, workloads/oslat/common.sh, workloads/scale-perf/common.sh, workloads/testpmd/common.sh
Depends-on: https://github.com/cloud-bulldozer/benchmark-operator/pull/763
=> Remove benchmark-operator's role dependencies

workloads/upgrade-perf/rosa_upgrade.sh
Some fields are required by Grafana to build graphs and cannot be null
=> Update ROSA metadata on upgrade-perf

workloads/upgrade-perf/rosa_upgrade.sh
It seems that 6 minutes could be not enough when command runs arround second 59
```
[2022-06-17 09:38:58,306] {subprocess.py:92} INFO - ++ date +%Y-%m-%d
[2022-06-17 09:38:58,307] {subprocess.py:92} INFO - ++ date -u '--date=+6 minutes' +%H:%M
[2022-06-17 09:38:58,308] {subprocess.py:92} INFO - + rosa upgrade cluster -c perf-410-e99e --version=4.10.18 -y --schedule-date 2022-06-17 --schedule-time 09:44
[2022-06-17 09:38:58,605] {subprocess.py:92} INFO - INFO: Ensuring account and operator role policies for cluster '1ssu1bvpit0o57ljqph8q1o5hpa3vrg5' are compatible with upgrade.
[2022-06-17 09:38:59,835] {subprocess.py:92} INFO - INFO: Account and operator roles for cluster 'perf-410-e99e' are compatible with upgrade
[2022-06-17 09:39:00,142] {subprocess.py:92} INFO - ERR: Failed to …
```
=> Increase scheduling time for rosa upgrades on 1 minute

workloads/kube-burner/build_helper.sh, workloads/kube-burner/builds/cakephp.sh
The cakephp image was not specific for our openshift versions and had failures at large scale 
When running multiple items in the BUILD_LIST, only the last 1 in the list's info was in the output file
=> Updating cakephp image 

utils/benchmark-operator.sh
It is confusing being able to set environment variables OPERATOR_REPO and OPERATOR_BRANCH when they aren't used to install the ripsaw-cli package at all, only the ripsaw operator apply. 
This will install the specified repo and branch depending on what env vars are set
=> Install specified version of ripsaw-cli

workloads/network-perf/README.md, workloads/network-perf/common.sh, workloads/network-perf/ripsaw-uperf-crd.yaml, workloads/network-perf/smoke-crd.yaml
Once https://github.com/cloud-bulldozer/benchmark-operator/pull/781 lands, we won't need to pin uperf pods anymore.
Also removing the multi_az implementation, this functionality is useless when we have a fresh deployed cluster, since these cluster usually have 3 or 4 machinesets using different AZs each one.
Removing all this stuff helps in simplifying the benchmark implementation quite a bit.
In case we're interested in providing a pin node feature (which is not available in the orig implementation),  it be addressed in a different PR to keep the original purpose of this one
=> Stop pinning uperf pods 

utils/benchmark-operator.sh
We're missing https://github.com/cloud-bulldozer/benchmark-operator/commit/11b3e099f217aa436c89f62ccfceda0462d3de8b in the v1.0.0 tag
=> Benchmark-operator v1.0.1

workloads/router-perf-v2/workload.py
MB tool is failing to record the right `delay`(latency) for non-200 response and hence affecting the overall P99 and P90 latency value. The more non-200 response the worse P99 latency value(1657660884527 second) due to the issue, this fix will only include 200 response for latency calculation.
This is a temporary work around while we work on the new benchmark-operator.
=> router-perf to exclude non-200 responses for latency 

workloads/kube-burner/common.sh
New-token is not going to be in the next release. Create should work for all versions
`
08-16 12:46:44.231  Command "get-token" is deprecated, and will be removed in the future version. Use oc create token instead.
08-16 12:46:44.529  error: could not find a service account token for service account "prometheus-k8s"
08-16 12:46:45.133  Command "new-token" is deprecated, and will be removed in the future version. Use oc create token instead.
`
=> adding create token instead of new-token

workloads/kube-burner/workloads/node-density-heavy/app-deployment.yml, workloads/kube-burner/workloads/node-density-heavy/postgres-deployment.yml
Replacing use of ":latest" in node-density-heavy with direct image hash.
... pods that have ContainerCreateError due to `pull QPS exceeded`.
=> Fix image versions instead of latest

workloads/kube-burner/README.md, workloads/kube-burner/common.sh, workloads/kube-burner/env.sh, workloads/kube-burner/run.sh, workloads/kube-burner/workloads/node-pod-density/node-pod-density.yml, workloads/kube-burner/workloads/node-pod-density/pod.yml
Scheduling labels, tolerations, and extra variables to customize node-density to run on specific nodes, in this case Windows workers.
See PERFSCALE-1848
=> Enable node-density lite on windows workers

workloads/network-perf/README.md, workloads/network-perf/env.sh
Stop running this test with 4 pairs, it doesn't add any value to the results in our current scenarios, as we're already using the full bandwidth of the instance with 2 pairs. As shown in the picture below
The the graph above, 4 pairs have similar throughput compared to 2 pairs. Apart from this, using more than 1 pair is only required to observe how 2 different process (uperf) behave at the time of sharing the network link
i.e
2 pairs 1024B: 4870 x 2 = 9740
4 pairs 1024B: 2460 x 4 = 9840
=> Remove 4 pairs scenario

workloads/kube-burner/run.sh
Node unlabel only when cleanup is set, this let us use node-density to pre-load cluster before [migration](https://github.com/cloud-bulldozer/e2e-benchmarking/pull/477) or upgrade.
=> unlabel node only on cleanup

workloads/prometheus-sizing/README.md, workloads/prometheus-sizing/common.sh, workloads/prometheus-sizing/env.sh, workloads/prometheus-sizing/prometheus-sizing-churning.yml, workloads/prometheus-sizing/prometheus-sizing-static.yml, workloads/prometheus-sizing/templates/pod.yml
Some fixes and additional configuration to run the prometheus-sizing workload on OCP 4.12 and OpenShift local 4.10.18.  
I can split this PR in pieces if you think it's best
- Correctly specify benchmark id for kube-burner destroy
- Adapt retrieval of auth token for Prometheus API for OCP 4.11 and later
- Update pod template security context
- Add options
- to dump collected metrics to `./collected-metric`
- to specify a different metrics file
=> Prometheus sizing ocp 1.12 fixes

workloads/kube-burner/workloads/node-pod-density/pod.yml
Need lower case effect to no get error defined in issue 
```
10-04 15:56:45.891  ###############################################
10-04 15:56:45.891  Workload: node-density
10-04 15:56:45.891  Workload template: workloads/node-pod-density/node-pod-density.yml
10-04 15:56:45.891  Metrics profile: metrics-profiles/metrics.yaml
10-04 15:56:45.891  Alerts profile: 
10-04 15:56:45.891  QPS: 20
10-04 15:56:45.891  Burst: 20
10-04 15:56:45.891  UUID: 60d12be0-2cd4-4270-9ca1-a620371f81e5
10-04 15:56:45.891  Node count: 3
10-04 15:56:45.891  Pods per node: 200
10-04 15:56:45.891  ###############################################
10-04 15:56:46.150  [1mTue Oct  4 19:56:46 UTC 2022 Indexing enabled, using metrics from metrics-profiles/metrics.yaml[0m
10-04 15:56:46.151 …
```
=> adding pod effect lower case

workloads/kube-burner/README.md, workloads/kube-burner/common.sh, workloads/kube-burner/env.sh, workloads/kube-burner/workloads/cluster-density/cluster-density.yml, workloads/kube-burner/workloads/managed-services/cluster-density.yml
The churn functionality has been added to kube-burner. This PR moves to using that native functionality instead of what is coded in e2e. This gives us the benefit of gathering the metrics from during the churn cycles as well as simplifying the e2e code base.
=> Migrate churn function to native kube-bruner functionality

utils/compare.sh, utils/csv_gen.py, utils/csv_modifier.py
Since I am setting the location of COMPARISON_OUTPUT by default this [line](https://github.com/cloud-bulldozer/e2e-benchmarking/blob/6e6dc1c895cba6cd42459ef28a99d05e5ba37219/utils/compare.sh#L62) no longer properly performs a check. Changing to be GEN_CSV 
Also adding in additional checks in the python scripts to validate csv files exist 
Files in comparison not existing and causing errors
```
10-06 13:23:49.917  [1mThu Oct  6 17:23:49 UTC 2022 python csv modifier[0m
10-06 13:23:50.479  Traceback (most recent call last):
10-06 13:23:50.479    File "/home/jenkins/ws/workspace/ltibranch-pipeline_kube-burner_5/utils/csv_modifier.py", line 73, in <module>
10-06 13:23:50.479      main()
10-06 13:23:50.479    File "/home/jenkins/ws/workspace/ltibranch-pipeline_kube-burner_5/utils/csv_modifier. …
```
=> Checks to see if compare files don't exist

workloads/kube-burner/README.md, workloads/kube-burner/run.sh, workloads/kube-burner/workloads/networkpolicy/README.md, workloads/kube-burner/workloads/networkpolicy/case1-networkpolicy.yml, workloads/kube-burner/workloads/networkpolicy/case1.yml, workloads/kube-burner/workloads/networkpolicy/deny-all.yml, workloads/kube-burner/workloads/networkpolicy/image/pod-scraper.py
Scenario as per README using [NetworkPolicy test cases](https://docs.google.com/document/d/1OQtOXtqqHzV79vJ04r3z1icv5b-9y5AtWGrEgUMnvEg) as reference
Some caveats:
* Since there does not seem to be away to have a different number of replicas in each namespace, used an average of 20 replicas per namespace
* The case uses un-enforced egress rules to provide some information to the pod scraper, unfortunately in OVN there is a bug that causes the selected pods to be isolated for egress even if the policy type is not set to egress. Fixed being worked on here: https://github.com/ovn-org/ovn-kubernetes/pull/3162
Signed-off-by: Jaime Caamaño Ruiz <jcaamano@redhat.com>
=> Add case 1 network policy workload

workloads/hyper-scale/common.sh
This PR adds the following tags to the HyperShift clusters 
1) User:${GITHUB_USER}
2) {MGMT_CLUSTER_NAME}:{HOSTED_CLUSTER_NAME}
Signed-off-by: Krishna Harsha Voora <krvoora@redhat.com>
=> Add Additional tags to Hypershift Clusters

utils/touchstone-configs/nodeAggWorkers.json, utils/touchstone-configs/nodeMasters-max.json
Changes to generate google sheets to support automated testing of:
https://issues.redhat.com/browse/OCPQE-11961 - OCP-40557 - Replace loaded worker nodes with larger instances
https://issues.redhat.com/browse/OCPQE-12152 - Extend automation for "OCP-40557 - Replace loaded worker nodes with larger instances" to other providers.
Passing Jenkins Runs:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/svetsa-e2e-benchmarking-multibranch-pipeline/job/regression-test/8/console
File generated: 
https://docs.google.com/spreadsheets/d/1jrnS05dd2p3WM63TIOXNYqW0KDWXoboSewYa3_hffXk/edit#gid=1321307691
=> New configs to support OCP-40557 polarion test case to replace loaded workers

workloads/router-perf-v2/common.sh, workloads/router-perf-v2/env.sh, workloads/router-perf-v2/ingress-performance.sh
Fixes: https://github.com/cloud-bulldozer/e2e-benchmarking/issues/487
This modifies the router tests to work with HyperShift Hosted Clusters since some of the control plane components (openshift-ingress-operator/openshift-cluster-version-operator) do not exist on the hsoted cluster and instead exist on a management cluster.
=> Modify router tests to work with HyperShift

workloads/router-perf-v2/common.sh
These two conditionals are incorrect and are always evaluated true
=> Fix hypershift conditionals

utils/touchstone-configs/netobserv_touchstone.json
updating for metrics added in [PR # 308](https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/308) and aws s3 storage metric.
=> NetObserv touchstone config update

workloads/kube-burner/build_helper.sh, workloads/kube-burner/builds/eap.sh
I updated the build_test.py script in the svt repo to use python3 packages instead of python2. Need to update this script to take out python 2 references 
Also the eap imagestream name had been updated and the concurrent-build script was not able to properly run that type of build
`Error "Error resolving ImageStreamTag jboss-eap64-openshift:latest in namespace openshift: imagestreams.image.openshift.io "jboss-eap64-openshift" not found" for field "from".`
=> Conc builds update to use python3 

workloads/kube-burner/workloads/node-density-heavy/app-deployment.yml
The location of the perfApp has been changed. Stop using the sha256 notation of it, as it breaks as soon as the image is updated.
cc: @afcollins
=> Update perfApp image location

workloads/router-perf-v2/common.sh
Hypershift tuned profile uses `Node Tuning Operator` but it has to be done on the Management cluster in a [different way](https://hypershift-docs.netlify.app/how-to/automated-machine-management/node-tuning/),  create a configmap and add it in to hc `nodepool` as tuning option. 
This PR enables it.
=> tuned profile for hypershift

workloads/kube-burner/common.sh
kube-burner script errors trying to find a path when running cluster-density.
```
[2023-02-01 22:21:09,629] {subprocess.py:92} INFO - time="2023-02-01 22:21:09" level=fatal msg="Error reading alert profile /home/airflow/workspace/e2e-benchmarking/workloads/kube-burner/alert-profiles/cluster-density-AWS.yml: /home/airflow/workspace/e2e-benchmarking/workloads/kube-burner/alert-profiles/cluster-density-AWS.yml is not a valid URL"
```
=> typo - alerts-profiles, not alert-profiles

workloads/kube-burner/README.md, workloads/kube-burner/run.sh, workloads/kube-burner/workloads/node-density-cni/node-density-cni.yml, workloads/kube-burner/workloads/node-density-heavy/node-density-heavy.yml, workloads/kube-burner/workloads/node-density-heavy/postgres-deployment.yml
Add postgres readinessProbe that helps performance.
Larger densities of node-density-cni and node-density-heavy workloads benefit from NAMESPACED_ITERATIONS=true.
A readiness probe on postgres helps reduce failure and restarts of the app-deployment.
=> Add cni and heavy namespaced iterations env.

utils/compare.sh, workloads/router-perf-v2/ingress-performance.sh
I hope the ingress-performance.sh can exit 1 when benchmark comparison fails, so that the CI calling ingress-performance.sh can get this result to set the CI test's final result.
Currently when set COMPARISON_RC=1, this line's return code is 1. https://github.com/cloud-bulldozer/e2e-benchmarking/blob/0bf6622531f2b1fed8ef7c332d2b42c083bd6a04/utils/compare.sh#L110 
As ingress-performance.sh has the `set -e` setting, https://github.com/cloud-bulldozer/e2e-benchmarking/blob/0bf6622531f2b1fed8ef7c332d2b42c083bd6a04/workloads/router-perf-v2/ingress-performance.sh#L2 
the rest codes in run_benchmark_comparison  after compare will not be executed.
https://github.com/cloud-bulldozer/e2e-benchmarking/blob/0bf6622531f2b1fed8ef7c332d2b42c083bd6a04/utils/compare.sh#L59-L68
This PR 
1 Set return code …
=> router-perf exit 1 when benchmark comparison fails

workloads/kube-burner/README.md, workloads/kube-burner/env.sh
Includes this important patch https://github.com/cloud-bulldozer/kube-burner/pull/240 that improves reported pod ready latencies.
=> Bump kube burner version to v0.17.3

workloads/kube-burner/pod-latency-tolerancy-rules.yaml
Want to add a pod latency tolerancy file to use in comparisons for getting final result of 
Need to address https://github.com/cloud-bulldozer/e2e-benchmarking/issues/540 to further look into all the data that can be collected with the [touchstone-configs](https://github.com/cloud-bulldozer/e2e-benchmarking/tree/master/utils/touchstone-configs)
=> Adding pod latency tolerancy for kube burner worklaod

workloads/kube-burner/README.md, workloads/kube-burner/common.sh, workloads/kube-burner/env.sh, workloads/kube-burner/run.sh
Added support to scrape multiple prometheus endpoints as in https://github.com/cloud-bulldozer/kube-burner/pull/251
Tested using below commands
``` 
LOG_LEVEL=debug WORKLOAD=pod-density PROM_URL=https://www.exampleurl.com METRICS_ENDPOINT=/home/vchalla/metrics endpoints.yaml ./run.sh 
```
``` 
LOG_LEVEL=debug WORKLOAD=pod-density METRICS_ENDPOINT=/home/vchalla/metrics-endpoints.yaml ./run.sh
```
```
LOG_LEVEL=debug WORKLOAD=pod-density ./run.sh
```
=> Adding multiple endpoints support for kube-burner workloads

workloads/router-perf-v2/env.sh, workloads/router-perf-v2/http-perf.yml, workloads/router-perf-v2/templates/nginx-deploy.yml
Currently we check for greater than or equal to 24 nodes excluding workload node to execute the large scenario. This means that even if you have a 24 worker cluster, you will actually end up running the small scale scenario since one node is excludded when counting total workers.
However, we still continue to use the workload node to place the backend nginx pods, which makes our logic of determining small/large scale senario and labeling the workload node counter-intuitive. The nginx backend pods are fighting for cpu time on the same node where mb client is firing requests off of.
This patch does the following:
1. Counts the workload node also when determining number of worker nodes (still excludes infra)
2. Exlcudes the workload node from backend pod placement using node anti-affinity …
=> Fix router large scale scenario

workloads/network-perf-v2/run.sh
Why?
- Reduce the test time
- Having multiple load-drivers in CI might confuse the results.
=> Removing iperf from the mix

workloads/kube-burner/common.sh
Kube-burner does not run as a pod anymore, there's no need to substract 1 to the result.
Also, the check should be done after dividing total_pod_count by 2 when the workload is node-density-heavy/cni
=> Fix total_pod_count check

workloads/network-perf-v2/env.sh, workloads/network-perf-v2/run.sh
Allow the user to override the default tolerance (20% delta). Setting the tolerance higher than currently observed delta.
=> Adding tolerance to network-v2

workloads/kube-burner-ocp-wrapper/README.md, workloads/kube-burner-ocp-wrapper/run.sh
Release notes: https://github.com/cloud-bulldozer/kube-burner/releases/tag/v1.6
=> Bump kube burner and fix confusing doc typos

workloads/network-perf-v2/env.sh
Two things to consider -
- 8192 single stream will struggle to match the throughput of hostNetwork.
- Cloud variance also causes flux. See below
The below podNetwork is pretty consistent run to run, but the hostNetwork experiences flux.
```
Run 1
+-------------------+---------+------------+-------------+--------------+---------+--------------+-----------+----------+---------+--------------------+---------------------------------+
|    RESULT TYPE    | DRIVER  |  SCENARIO  | PARALLELISM | HOST NETWORK | SERVICE | MESSAGE SIZE | SAME NODE | DURATION | SAMPLES |     AVG VALUE      |     95% CONFIDENCE INTERVAL     |
+-------------------+---------+------------+-------------+--------------+---------+--------------+-----------+----------+---------+--------------------+--------------------------- …
```
=> Update netperf-v2 tolerance

.gitignore, utils/compare.sh
The NetObserv team is increasing our usage of `compare.sh` so wanted to make some contributions to clean up the file a bit and make it easier to potentially extend in the future
- Small typo fix
- Formatting
- Adds additional comments
- Stops CSVs generated in `utils` directory from being tracked
=> Cleaned up 'compare.sh' and added add'l comments

workloads/kube-burner/common.sh
Removing label from the workedr node is timing out on a 120 node environment. Instead of using one command to remove labels on all worker nodes, we iterate through each worker node and remove label on it.
- Related Issue #585 
- Closes #585
=> fix label timeout

workloads/ingress-perf/README.md
The README.md now points to `config/aws-standard.yaml`
- Closes #
=> [doc-updates]: To ingress-perf README.md

workloads/ingress-perf/run.sh, workloads/kube-burner-ocp-wrapper/run.sh
Updating kube-burner and ingress-perf binary versions.
- Closes #
=> Bumping kube-burner & ingress-perf versions

utils/compare.sh, workloads/kube-burner/pod-latency-tolerancy-rules.yaml
The current comparison code has an option to add multiple config files to generate a csv file. Want to be able to also specify multiple tolerancy comparison files to use when determining pass/fail of a test
I am also editing the pod latency tolerancy file that is in the kube-burner workload because the Initialized and PodScheduled latencies have been 0 a lot recently and it causes a divide by 0 error 
- Related Work [OCPQE-13796](https://issues.redhat.com/browse/OCPQE-13796)
Comparing with baseline 
export COMPARISON_CONFIG="podLatency.json nodeMasters.json nodeWorkers.json etcd.json crio.json kubelet.json"
export TOLERANCY_RULES=pod-latency-tolerancy-rules.yaml master-tolerancy.yaml worker-tolerancy.yaml etcd-tolerancy.yaml crio-tolerancy.yaml kubelet-tolerancy.yaml
Tolerancy files are …
=> Mutli Tolerancy comparison

workloads/kube-burner-ocp-wrapper/run.sh
Minor change, UUID set by the airflow job gets overridden by this so logs have 2 different IDs, changed it to generate only if not set by the user. 
- Closes #
=> uuidgen only if not set

workloads/baseline-performance/README.md, workloads/baseline-performance/baseline_perf.sh, workloads/baseline-performance/common.sh, workloads/prometheus-sizing/README.md, workloads/prometheus-sizing/common.sh, workloads/prometheus-sizing/env.sh, workloads/router-perf-v2/README.md, workloads/router-perf-v2/common.sh, workloads/router-perf-v2/env.sh
By default, use always last version of kube-burner downloading latest from github release.
But, if anytime we need to select an specific version, current variable **KUBE_BURNER_RELEASE_URL** is still available in the same way that we were using until now
- Closes #
=> Use latest version of kube-burner as default but allow to select a fixed one

workloads/kube-burner-ocp-wrapper/run.sh, workloads/kube-burner/README.md, workloads/kube-burner/common.sh, workloads/kube-burner/env.sh
Defaulting latest version of kube-burner along with an option to specify a version. Similar to this [change](https://github.com/cloud-bulldozer/e2e-benchmarking/pull/603).
- Closes #
Tested and verified in self managed cluster.
```
[vchalla@vchalla kube-burner-ocp-wrapper]$ KUBE_BURNER_VERSION=latest WORKLOAD=node-density ./run.sh 
/tmp/kube-burner ocp node-density --log-level=info --qps=20 --burst=20 --gc=true --uuid c8963dd0-423d-48f4-a26b-de5b6eb01461 --es-server=https://search-perfscale-dev-chmf5l4sh66lvxbnadi4bznl3a.us-west-2.es.amazonaws.com --es-index=ripsaw-kube-burner
time="2023-08-06 16:58:58" level=info msg="File node-density.yml available in the current directory, using it" file="helpers.go:177"
time="2023-08-06 16:58:58" level=info msg="📁 Creating indexer: …
```
=> Defaulting kube-burner version to latest

utils/index.sh
Keeping a single index for CI related runs to avoid further mapping issues. And also to keep them separate envisioning our dash-boarding work.
- Closes # https://github.com/cloud-bulldozer/e2e-benchmarking/issues/605
Tested on my local dev environment.
=> Marking perf_scale_ci index as hardcoded value for CI data

utils/index.sh
on Hosted cluster jobs, json exception due to missing master nodes
```
oc get nodes -l node-role.kubernetes.io/master -o 'jsonpath={.items[].metadata.labels.beta\.kubernetes\.io/instance-type}'
error: error executing jsonpath "{.items[].metadata.labels.beta\\.kubernetes\\.io/instance-type}": Error executing template: array index out of bounds: index 0, length 0. Printing more information for debugging the template:
template was:
{.items[].metadata.labels.beta\.kubernetes\.io/instance-type}
object given to jsonpath engine was:
map[string]interface {}{"apiVersion":"v1", "items":[]interface {}{}, "kind":"List", "metadata":map[string]interface {}{"resourceVersion":""}}
```
- Closes #
- Please provide detailed steps to perform tests …
=> json error if missing, added `--ignore-not-found`

workloads/network-perf-v2/run.sh
oc create ns fails if it already exists
```
./run.sh
Error from server (AlreadyExists): namespaces "netperf" already exists
```
- Closes #
=> create ns only if not exists already

workloads/baseline-performance/README.md, workloads/baseline-performance/baseline_perf.sh, workloads/baseline-performance/common.sh, workloads/kube-burner-ocp-wrapper/run.sh, workloads/kube-burner/README.md, workloads/kube-burner/common.sh, workloads/kube-burner/env.sh, workloads/prometheus-sizing/README.md, workloads/prometheus-sizing/common.sh, workloads/prometheus-sizing/env.sh, workloads/router-perf-v2/README.md, workloads/router-perf-v2/common.sh, workloads/router-perf-v2/env.sh
This reverts commit 3cd258cae8ac358788badd99da79055261a84870.
I think we should revert these changes, I've reconsidered my thoughts for several reasons:
- Using a fixed kube-burner version guarantees backwards compatibility and should be generally more stable: A breaking change on kube-burner won't break any benchmark
- Better issue traceability: Identifying a bug should be easier, specially for CPT runs
- We should decide when and when not to bump the kube-burner version. i.e: Sometimes new releases just ship some bug fixes not affecting any of the functionality available within this repository. Continuously changing the kube-burner version without justification is not recommended and can be confusing when reviewing results
- Related Issue #619
- Closes #
=> Revert "Defaulting kube-burner version to latest

workloads/kube-burner-ocp-wrapper/run.sh
For hypershift we use kube-burner index to scrape metrics during creation/deletions of clusters to record the MC perf, so instead of re-implementing these(multi-endpoint prep) in rosa-burner it would be easy to use the same script with a conditional tasks. 
WORKLOAD=index --> will only call kube-burner index for the given duration START_TIME & END_TIME
- Closes #
=> Use workload script to call kube-burner index

workloads/network-perf-v2/run.sh
PROW hcp data-path [runs](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/44173/rehearse-44173-periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.13-nightly-x86-perfscale-rosa-hcp-3zones-data-path-9nodes-periodic/1712143864896163840) fail on this error
HCs don't have this resource.
```
error: the server doesn't have a resource type "machineset"
```
- Closes #
=> silencing debug errors for hcp

workloads/kube-burner-ocp-wrapper/run.sh
With the current shell parameter expansion used its not possible to disable indexing when ES_SERVER is set and null. Using the expansion expression ${parameter=word} fixed the issue. reference:
- Closes #
```shell
$ WORKLOAD=node-density ./run.sh 
/tmp/kube-burner ocp node-density --log-level=info --qps=20 --burst=20 --gc=true --uuid 7e2ada0b-593f-4c37-b2a3-e5e66b306e2e --es-server=https://search-perfscale-dev-chmf5l4sh66lvxbnadi4bznl3a.us-west-2.es.amazonaws.com --es-index=ripsaw-kube-burner
etc.
$ ES_SERVER="" WORKLOAD=node-density ./run.sh 
/tmp/kube-burner ocp node-density --log-level=info --qps=20 --burst=20 --gc=true --uuid b621855a-cfb2-483a-9bb8-1f9c30586abe
```
=> Fix disabling indexing

utils/index.sh
index.sh prints a lot of lines needlessly, which makes more difficult to find a relevant log line, let's try to keep a clean stdout.
=> Fixing noisy index.sh script

workloads/kube-burner-ocp-wrapper/metrics-profiles/hosted-cluster-metrics.yml, workloads/kube-burner-ocp-wrapper/metrics-profiles/hosted-cp-metrics.yml
API latency metrics scrapped by OBO are only for SRE alerting purpose, they are limited to collect only few buckets to save storage due to its volume.  But all KAPI metrics are forwarded to guest cluster side as well for user benefits, we should be able to scrape them from hosted cluster prometheus instance, so moving API latency metrics to hosted-cluster-metric profile will be the right approach for our reports.
- Closes #
=> moved api latency queries to guest side

workloads/ingress-perf/config/standard-classic-rosa.yml
Because of the size of the infra nodes when installing rosa, we need to decrease this parameter to 5
=> Decrease concurrency to 5 on router tests for rosa

utils/index.sh
NetObserv needs UNIX timestamps for start and end dates for the [NOPE](https://github.com/openshift-qe/ocp-qe-perfscale-ci/blob/netobserv-perf-tests/scripts/nope.py) tool - previously we got them from Mr. Sandman but that functionality never made it over here
- Related Issue: [NETOBSERV-1449](https://issues.redhat.com/browse/NETOBSERV-1449)
To come
=> Add unix timestamps for start and end date to payload

workloads/ingress-perf/config/standard-classic-rosa.yml, workloads/ingress-perf/config/standard.yml
We need to cut down the duration of some of our tests.
Ideally I'd like to drop it to 2m, but since it's collecting some prometheus metrics I think is better to collect couple of more datapoints (30s each) to get a better data quality.
- Closes #
=> Dropping ingress-perf runtime

utils/index.sh
Sometimes when we are getting indexed details, the publish field has extra spaces and new lines in the front of the value that makes the elastic search post not succeed in posting.
I have seen this from time to time on both Prow and jenkins but only for the publish field specifically, I can add to other calls as well if wanted
Example: 
```
{
"ciSystem":"PROW",
"uuid":"3c484837-565c-4ba3-b483-dcb1d02d38e6",
"releaseStream":"4.15.0-0.nightly",
"platform":"Azure",
"clusterType":"self-managed",
"benchmark":"k8s-netperf",
"masterNodesCount":3,
"workerNodesCount":9,
"infraNodesCount":3,
"masterNodesType":"Standard_D8s_v3",
"workerNodesType":"Standard_D4s_v3",
"infraNodesType":"Standard_D16s_v3",
"totalNodesCount":15,
"clusterName":"ci-op-kqwvgvbh-c8ba2-pcstz", …
```
=> Taking out all spaces in value publish

ci/CI_test_list.yml, ci/env.sh, workloads/kube-burner/README.md
The workload's on this directory shouldn't be used anymore, people should use https://github.com/cloud-bulldozer/e2e-benchmarking/tree/master/workloads/kube-burner-ocp-wrapper going forward.
=> Deprecate legacy kube-burner workload

workloads/ingress-perf/run.sh, workloads/kube-burner-ocp-wrapper/run.sh, workloads/network-perf-v2/run.sh
When  curl  is  about to retry a transfer, it will first wait one second and then for all forthcoming retries it will double the waiting time until it reaches 10 minutes...
Regarding the `--retry-all-errors` flag, taken from the cURL docs
> By  default  curl will not error on an HTTP response code that indicates an HTTP error, if the transfer was successful. For example, if a server replies 404 Not Found and the reply is fully received then that is not an error. When --retry is used then curl will retry on some HTTP response codes that indicate transient HTTP errors, but that does not include most 4xx response codes such as 404. If you want  to  retry  on  all  response codes that indicate HTTP errors (4xx and 5xx) then combine with -f, --fail.
=> PERFSCALE-2825: Add curl retry flags

utils/index.sh
Previously timestamp field used to use the job start time. Updated it to use the current timestamp.
Tested in local in a hacky way.
```
[vchalla@vchalla-thinkpadp1gen2 e2e-benchmarking]$ current_timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
[vchalla@vchalla-thinkpadp1gen2 e2e-benchmarking]$ echo $current_timestamp
2024-04-15T18:21:00Z
```
=> Updating timestamp value to use current timestamp

workloads/kube-burner-ocp-wrapper/metrics-endpoint.yml
Updating metrics-endpoint file to be in sync with latest kb changes.
Tested in local
```
[vchalla@vchalla-thinkpadp1gen2 kube-burner-ocp]$ kube-burner-ocp cluster-density-v2 --log-level=info --qps=20 --burst=20 --gc=true --uuid 78cf9e75-1d7a-407f-98cc-a389e0ed4852 --gc-metrics=true --profile-type=reporting --gc-metrics=true --profile-type=reporting --iterations=1 --churn=true --es-server='https://ocp-qe:Perfscale24!@search-ocp-qe-perf-scale-test-elk-hcm7wtsqpxy7xogbu72bor4uve.us-east-1.es.amazonaws.com' --es-index=ripsaw-kube-burner --metrics-endpoint=metrics-endpoint.yml --log-level=debug
time="2024-05-10 16:00:44" level=info msg=metrics-endpoint.yml file="helpers.go:96"
time="2024-05-10 16:00:44" level=info msg="📁 Creating opensearch indexer: indexer-0" file="metrics.go:62" …
```
=> Updating metrics-endpoint file to sync with latest kb changes

utils/index.sh
Fixing build url for rehearsel jobs in prow. Currently its broken because it uses the same logic for both PRs and periodic jobs
Look at the build urls for any of the jobs [here](http://dashboard.apps.sailplane.perf.lab.eng.rdu2.redhat.com/ocp?ciSystem=All&platform=All&benchmark=All&version=All&workerCount=All&networkType=All&jobType=All&isRehearse=TRUE&ipsec=All&fips=All&encrypted=All&encryptionType=All&publish=All&computeArch=All&controlPlaneArch=All&startDate=2024-05-07&endDate=2024-05-12), they are broken. Wherein here they are working because they are [periodic jobs](http://dashboard.apps.sailplane.perf.lab.eng.rdu2.redhat.com/ocp?ciSystem=All&platform=All&benchmark=All&version=All&workerCount=All&networkType=All&jobType=All&isRehearse=FALSE&ipsec=All&fips=All&encrypted=All&encryptionT …
=> build url fix for rehearsel jobs

workloads/kube-burner-ocp-wrapper/metrics-profiles/metrics-aggregated.yml, workloads/kube-burner-ocp-wrapper/metrics-profiles/metrics-report.yml, workloads/kube-burner-ocp-wrapper/metrics-profiles/metrics.yml, workloads/kube-burner-ocp-wrapper/run.sh
The idea is to add a reusable index step in PROW and invoke a know list of metrics profiles. PR in PROW: https://github.com/openshift/release/pull/51249. So adding metrics profiles in the kube-burner-ocp-wrapper directory so that they can be invoked from PROW for indexing post run metrics.
Tested integrating with this PR:https://github.com/openshift/release/pull/51249
=> Adding metric profiles for index step

workloads/kube-burner-ocp-wrapper/run.sh
The ITERATIONS parameters does not make sense in web-burner scenarios.
=> Discard ITERATIONS when running web-burner

prow/Dockerfile
Latest  binary doesn't works in this container image...
```shell
INFO[2024-07-05T14:49:12Z] + cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
+ oc config view
oc: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by oc)
oc: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by oc) 
```
- Closes #
- How were the fix/results from this change verified? Please provide relevant …
=> Fixing broken oc binary

workloads/ingress-perf/config/standard-scalelab.yml
cc @jtaleric @josecastillolema 
Still, WIP, but is a starting point.
Note: default number of threads is 4, the r760 servers of the scalelab have 64 physical CPUs, which means that with the default configuration, haproxy doesn't take advantage from most of the resources available
- Closes #
=> Ingress-perf config for scalelab CPT jobs

prow/Dockerfile
To fix the failing CI test here: https://github.com/cloud-bulldozer/e2e-benchmarking/pull/718
Needs to be tested in prow.
=> Updating prow docker file

workloads/network-perf-v2/env.sh, workloads/network-perf-v2/run.sh
Allow the user to set env var of "VIRT" to set VM network performance test.
- Closes #
=> Adding Virt for k8s-netperf

workloads/kube-burner-ocp-wrapper/run.sh
Adding workers-scale compatibility to kube-burner-ocp wrapper.
Needs to be verified through a PR in prow.
=> Adding workers-scale compatibility

workloads/kube-burner-ocp-wrapper/metrics-profiles/workers-scale/metrics-report.yml, workloads/kube-burner-ocp-wrapper/metrics-profiles/workers-scale/metrics.yml
Adding metric profiles that can be used during workers-scale workload.
Follow up on worker-scale workload recently added into kube-burner ocp wrapper.
Tested in local. Needs to be verified through one of the prow jobs as well.
=> Adding metrics for workers-scale

workloads/kube-burner-ocp-wrapper/metrics-profiles/workers-scale/metrics-report.yml, workloads/kube-burner-ocp-wrapper/metrics-profiles/workers-scale/metrics.yml, workloads/kube-burner-ocp-wrapper/run.sh
Adding enhancements for workers scale and in for kube-burner in overall. Has all the changes incorporated in this PR: https://github.com/kube-burner/kube-burner-ocp/pull/136 as part of the release.
Will be verified through PR rehearsal jobs.
=> Enhancements for workers-scale

utils/index.sh
Adding job types to CI fingerprint.
- Closes # https://github.com/cloud-bulldozer/e2e-benchmarking/issues/743
Tested in local in a hacky way.
1. Jenkins
```
vchalla@vchalla-thinkpadp1gen2:~/myforks/e2e-benchmarking$ curl -s "$JENKINS_JOB_URL" | jq -r '.actions[].causes[].shortDescription' 2>/dev/null
Started by upstream project "scale-ci/e2e-benchmarking-multibranch-pipeline/loaded-upgrade" build number 1,920
Started by user Meha Bhalodiya
Rebuilds build #2,086
```
2. Prow - Followed the docs to make use of ENVs: https://docs.prow.k8s.io/docs/jobs/
3. Airflow - Looked at other usage of Airflow Envs: https://github.com/search?q=AIRFLOW_CTX_DAG_RUN_ID&type=code&p=1
=> Adding job_type to the fingerprint index

utils/index.sh
Hitting an error when trying to get job details for jenkins
```
echo $build_url | jq -r ".actions[0].causes[0].shortDescription"
jq: parse error: Invalid string: control characters from U+0000 through U+001F must be escaped at line 2, column 14
```
Once I added in the "tr" of the new lines to spaces it passes 
```
echo $build_url | tr '\n' ' ' | jq -r ".actions[0].causes[0].shortDescription" 
Started by user Paige Patton
```
The command to get the latest cause causes the whole file to fail and no indexing occurs
it passes when commenting out the **set -eo pipefail**
https://jenkins-csb-openshift-qe-mastern.dno.corp.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/kube-burner-ocp/2120/console
fails if not: 
https://jenkins-csb-openshift-qe-mastern.dno.corp.redhat.com/jo …
=> Take out new lines and don't fail on null

prow/Dockerfile
Keeping Dockerfile inline with openshift CI: https://github.com/openshift-qe/ocp-qe-perfscale-ci/blob/main/prow/Dockerfile so that we can run all our e2e CI tests.
- Related Issue # https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/62205/rehearse-62205-pull-ci-cloud-bulldozer-e2e-benchmarking-master-e2e-egressip-single-node/1895452047755448320
Will verify through e2e tests in this PR.
=> Updaing dockerfile to be inline with openshift CI

workloads/kube-burner-ocp-wrapper/run.sh
Looks like we add --perf-profile flag to all workloads while it is only supported by rds-core
- Closes #
- [ X] I have performed a self-review of my code.
s.
=> Only rds-core workload supports the perf-profile flag

workloads/network-perf-v2/README.md, workloads/network-perf-v2/env.sh, workloads/network-perf-v2/run.sh
This enables user to call k8s-netperf with serverIP flag to send traffic to external server. User has to configure external server with the required k8s-netperf driver.
Usage:
export EXTERNAL_SERVER_ADDRESS=10.0.61.54;./run.sh
=> Use k8s-netperf's serverIP flag

workloads/ingress-perf/run.sh
[ingress-perf] add GATEWAY_API env to enable gateway api
- Related Issue # https://issues.redhat.com/browse/PERFSCALE-3653
Passed job
https://jenkins-csb-openshift-qe-mastern.dno.corp.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/ingress-perf/583/ 
````
03-18 17:44:26.349  ./ingress-perf run --cfg config/standard.yml --loglevel=info --uuid d482deba-5496-41c9-9a73-74ba4892fc10 --es-server=https://ocp-qe:****@search-ocp-qe-perf-scale-test-elk-hcm7wtsqpxy7xogbu72bor4uve.us-east-1.es.amazonaws.com --es-index=ingress-performance --gateway-api=true
03-18 17:44:28.230  time="2025-03-18 09:44:27" level=info msg="Gateway API mode enabled" file="runner.go:254"
````
=> [ingress-perf] add GATEWAY_API env to enable gateway api

utils/index.sh
No point checking for additional stuff when CNV operator itself is not installed. Otherwise, the error logs in Prow are an eyesore.
The Prow build logs are an eyesore when we keep checking for CNV related stuff even when the oeprator itself doesn't exist on the cluster: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_release/62845/rehearse-62845-periodic-ci-openshift-eng-ocp-qe-perfscale-ci-main-aws-4.19-nightly-x86-control-plane-120nodes/1902075016258785280/artifacts/control-plane-120nodes/openshift-qe-cluster-density-v2/build-log.txt
```
error: error executing jsonpath "{.items[0].spec.version}": Error executing template: array index out of bounds: index 0, length 0. Printing more information for debugging the template:
template was: …
```
=> Make additional Virt metadata capturing optional

workloads/kube-burner-ocp-wrapper/run.sh
- [.] Bug fix
remove the iteration var for netpol workload as it is set in extra flags
avoids prwo error
```
+ [[ network-policy =~ ^(crd-scale|pvc-density|network-policy)$ ]]
./run.sh: line 140: ITERATIONS: parameter null or not set
```
=> remove the iteration var for netpol workload as it is set in extra flags

workloads/kube-burner-ocp-wrapper/run.sh
Address the below error introduced by https://github.com/openshift/release/pull/65072, full log: https://gcsweb-qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/qe-private-deck/pr-logs/pull/openshift_release/65072/rehearse-65072-periodic-ci-openshift-openshift-tests-private-release-4.20-amd64-nightly-olmv1-benchmark-test/1941080918672281600/artifacts/olmv1-benchmark-test/olmv1-performance/build-log.txt
```console
+ /tmp/kube-burner-ocp olm --log-level=debug --qps=20 --burst=20 --gc=true --uuid 778b69c7-577d-4e24-8b6a-d3470d2b7f59 --churn-duration=5m --timeout=30m --metrics-profile=/tmp/olm-metrics.yml,/tmp/extended-metrics.yml --gc-metrics=false --profile-type=both --es-server=https://XXXXXX:XXXXXXXXXXXXXXXXXXXXXX@search-XXXXXX-perf-scale-test-elk-hcm7wtsqpxy7xogbu72bor4uve.us-east …
```
=> add iterations for olm workload

workloads/kube-burner-ocp-wrapper/run.sh
`kube-burner-ocp index` job won't accept `--pprof` argument as it is not necessary for such jobs, so overwriting it here to avoid failures.
=> disable pprof for index workload

workloads/kube-burner-ocp-wrapper/run.sh
Remove PPROF env var logic, this logic will be handled from openshfit/release side as the env var does not work anymore (it's interpreted as string, and that makes the [kube-burner template](https://github.com/kube-burner/kube-burner-ocp/blob/main/cmd/config/node-density/node-density.yml#L11) conditional true)
=> Remove PPROF env var

workloads/kube-burner-ocp-wrapper/run.sh
This PR adjusts the kube-burner-ocp wrapper to download binaries matching current OS and HW instead of using hardcoded values.
- Closes #
=> kube-burner-ocp-wrapper: auto-detect OS and hardware before downloading the binary

workloads/logging/env.sh, workloads/logging/files/logging-stack.yml
The `cluster-logging` and `elasticsearch-operator` don't use the same channel, so, we shouldn't use the same env var for them. 
```console
- message: 'constraints not satisfiable: no operators found in channel stable-5.8
of package cluster-logging in the catalog referenced by subscription cluster-logging,
subscription cluster-logging exists'
reason: ConstraintsNotSatisfiable
status: "True"
type: ResolutionFailed
```
- Closes #
=> update channels for logging

utils/index.sh
Handle cases when a periodic job is triggered from a PR, similar to https://github.com/openshift/kubernetes/pull/2394#issuecomment-3189823480
This is causing false positives in orion as is considering it a payload job.
- Related Issues:
- https://github.com/openshift/kubernetes/pull/2394#issuecomment-3189823480 
- https://github.com/cloud-bulldozer/orion/pull/191
=> Handle cases when a periodic job is triggered via PR

utils/index.sh
Currently UUID is only available in workload logs file, writing to a file would help us identify UUID for specific workloads without relying on log parsing.
- Closes #
=> write uuid to a file

workloads/kube-burner-ocp-wrapper/run.sh
kube-burner AI needs CI runs for cdv2 job with different config options.
We want cdv2 to run with varibale iteration count to have different number of namespaces across test runs.
E2E also uses my private kube burner repo which for the cdv2, creates variable number of cluster resources in each test run instead of predefined number of them. Each iteration in the test run, choses a random number between the min and max provided for the resource.
Please don't review or merge this change as it is a temporary change for our CI runs.
- Closes #
=> custom config for cluster density
